// Auto-généré — données Major 6AF
// courses.json + exercises.js fusionnés pour le site web

// Packs 6AF arabes — les QR des cahiers imprimés pointent sur ces ids
import { MATH6_LESSONS_1, MATH6_EXERCISES_1 } from './content-6af/math6-lessons-1.js'
import { MATH6_LESSONS_2, MATH6_EXERCISES_2 } from './content-6af/math6-lessons-2.js'
import { SCI6_LESSONS, SCI6_EXERCISES } from './content-6af/sci6-lessons.js'
import { AR6_LESSONS_1, AR6_EXERCISES_1 } from './content-6af/ar6-lessons-1.js'
import { AR6_LESSONS_2, AR6_EXERCISES_2 } from './content-6af/ar6-lessons-2.js'
import { ISL6_LESSONS, ISL6_EXERCISES } from './content-6af/isl6-lessons.js'
import { HG6_LESSONS_1, HG6_EXERCISES_1 } from './content-6af/hg6-lessons-1.js'
import { HG6_LESSONS_2, HG6_EXERCISES_2 } from './content-6af/hg6-lessons-2.js'
import { CIV6_LESSONS, CIV6_EXERCISES } from './content-6af/civ6-lessons.js'

export const COURSES = {
  "version": "1.0",
  "pays": "Mauritanie",
  "niveau": "6ème Année Fondamentale (6AF)",
  "concours": "Concours d'entrée au Premier Cycle Secondaire",
  "subjects": [
    {
      "id": "math",
      "label": "Mathématiques",
      "labelAr": "الرياضيات",
      "color": "#fb923c",
      "gradient": ["#f59e0b", "#f97316"],
      "icon": "📐",
      "lessons": [
        {
          "id": "math-fractions-base",
          "title": "Les Fractions — Addition & Soustraction",
          "qrCode": "major://lesson/math-fractions-base",
          "emoji": "➕",
          "difficulty": 1,
          "duration": "5 min",
          "summary": "Une fraction a/b représente a parties sur b. Pour additionner ou soustraire deux fractions, elles doivent avoir le MÊME dénominateur. Si ce n'est pas le cas, on cherche le dénominateur commun.",
          "keyPoints": [
            "3/4 + 1/4 = 4/4 = 1 → dénominateurs égaux : on additionne les numérateurs",
            "1/3 + 1/4 → dénominateur commun = 12 → 4/12 + 3/12 = 7/12",
            "Pour soustraire : même règle — même dénominateur d'abord",
            "Une fraction égale à 1 entier : a/a = 1 (ex. 6/6 = 1)"
          ],
          "rule": "a/b + c/b = (a+c)/b   |   a/b - c/b = (a-c)/b",
          "tip": "🧠 Astuce du champion : cherche TOUJOURS le dénominateur commun avant de calculer !",
          "encouragement": "Tu maîtrises les fractions ? Tu es déjà plus fort que 80% des élèves ! 🏆",
          "quizIds": ["m1", "m3"]
        },
        {
          "id": "math-fractions-mult",
          "title": "Les Fractions — Multiplication & Division",
          "qrCode": "major://lesson/math-fractions-mult",
          "emoji": "✖️",
          "difficulty": 2,
          "duration": "5 min",
          "summary": "Multiplier deux fractions : on multiplie les numérateurs entre eux ET les dénominateurs entre eux. Diviser par une fraction : on multiplie par son inverse (on retourne la fraction).",
          "keyPoints": [
            "2/3 × 3/4 = (2×3)/(3×4) = 6/12 = 1/2",
            "2/3 ÷ 4/5 = 2/3 × 5/4 = 10/12 = 5/6",
            "Fraction d'une quantité : 3/4 de 120 = (3 × 120) ÷ 4 = 90",
            "Simplifier avant de multiplier pour gagner du temps"
          ],
          "rule": "a/b × c/d = (a×c)/(b×d)   |   a/b ÷ c/d = a/b × d/c",
          "tip": "🧠 Astuce : simplifie AVANT de multiplier pour avoir de petits nombres !",
          "encouragement": "La multiplication de fractions, c'est ton arme secrète pour le concours ! 🚀",
          "quizIds": ["m2", "m6"]
        },
        {
          "id": "math-pourcentages",
          "title": "Pourcentages & Fractions d'une quantité",
          "qrCode": "major://lesson/math-pourcentages",
          "emoji": "%",
          "difficulty": 2,
          "duration": "6 min",
          "summary": "Un pourcentage, c'est une fraction de dénominateur 100. 25% = 25/100 = 1/4. Pour calculer un pourcentage d'une quantité, on multiplie la quantité par le pourcentage.",
          "keyPoints": [
            "25% de 200 = (25 × 200) ÷ 100 = 50",
            "10% d'un nombre : on divise par 10",
            "50% d'un nombre : on divise par 2",
            "75% = 3/4 d'un nombre",
            "Pour trouver le pourcentage : (partie ÷ total) × 100"
          ],
          "rule": "x% de N = (x × N) ÷ 100",
          "tip": "🧠 Mémorise : 10%=÷10, 25%=÷4, 50%=÷2, 75%=×3÷4",
          "encouragement": "Les pourcentages reviennent chaque année au concours. Tu les connais maintenant ! 💪",
          "quizIds": ["m2", "m6"]
        },
        {
          "id": "math-pgcd",
          "title": "PGCD & Fractions Irréductibles",
          "qrCode": "major://lesson/math-pgcd",
          "emoji": "🔢",
          "difficulty": 2,
          "duration": "7 min",
          "summary": "Le PGCD (Plus Grand Commun Diviseur) est le plus grand nombre qui divise exactement deux nombres. On l'utilise pour simplifier une fraction à sa forme irréductible.",
          "keyPoints": [
            "Diviseurs de 12 : 1, 2, 3, 4, 6, 12",
            "Diviseurs de 18 : 1, 2, 3, 6, 9, 18",
            "PGCD(12, 18) = 6",
            "12/18 ÷ 6/6 = 2/3 (fraction irréductible)",
            "Une fraction est irréductible quand PGCD(numérateur, dénominateur) = 1"
          ],
          "rule": "Fraction irréductible : numérateur et dénominateur divisés par leur PGCD",
          "tip": "🧠 Liste les diviseurs des deux nombres et cherche le plus grand en commun !",
          "encouragement": "Le PGCD c'est comme trouver le meilleur ami commun de deux nombres. Tu peux le faire ! 🌟",
          "quizIds": ["m8"]
        },
        {
          "id": "math-proportionnalite",
          "title": "Proportionnalité",
          "qrCode": "major://lesson/math-proportionnalite",
          "emoji": "⚖️",
          "difficulty": 2,
          "duration": "6 min",
          "summary": "Deux grandeurs sont proportionnelles quand leur rapport est toujours le même. On utilise la règle de trois (produit en croix) pour trouver une valeur manquante.",
          "keyPoints": [
            "Si 3 cahiers coûtent 15 Dh, alors 7 cahiers coûtent ?",
            "Produit en croix : 3 × ? = 7 × 15 → ? = 105 ÷ 3 = 35 Dh",
            "Tableau de proportionnalité : × par le même coefficient",
            "Vitesse constante = proportionnalité entre distance et temps"
          ],
          "rule": "a/b = c/d ↔ a × d = b × c (produit en croix)",
          "tip": "🧠 Fais toujours un tableau avec les unités pour ne pas te tromper !",
          "encouragement": "La proportionnalité est dans CHAQUE concours depuis 2005 ! Tu la maîtrises maintenant ! 🎯",
          "quizIds": ["m9"]
        },
        {
          "id": "math-vitesse",
          "title": "Vitesse — Distance — Temps",
          "qrCode": "major://lesson/math-vitesse",
          "emoji": "🚀",
          "difficulty": 2,
          "duration": "6 min",
          "summary": "La vitesse, la distance et le temps sont liés par une formule. Si tu connais deux des trois valeurs, tu peux toujours trouver la troisième.",
          "keyPoints": [
            "Distance = Vitesse × Temps",
            "Vitesse = Distance ÷ Temps",
            "Temps = Distance ÷ Vitesse",
            "Attention aux unités ! km/h, m/s, minutes…",
            "1 heure 30 min = 1,5 heure"
          ],
          "rule": "D = V × T   |   V = D ÷ T   |   T = D ÷ V",
          "tip": "🧠 Mémorise le triangle magique : D en haut, V et T en bas !",
          "encouragement": "Un champion calcule vite ET sans erreurs d'unités. Toi, tu peux ! ⚡",
          "quizIds": ["m9"]
        },
        {
          "id": "math-perimetre-aire",
          "title": "Périmètre & Aire des Figures",
          "qrCode": "major://lesson/math-perimetre-aire",
          "emoji": "📏",
          "difficulty": 1,
          "duration": "8 min",
          "summary": "Le périmètre est la longueur du contour d'une figure (en cm, m…). L'aire est la surface à l'intérieur d'une figure (en cm², m²…). Ce sont deux choses différentes !",
          "keyPoints": [
            "Carré : P = 4×c | A = c²",
            "Rectangle : P = 2×(L+l) | A = L×l",
            "Triangle : P = somme des 3 côtés | A = (base×hauteur)÷2",
            "Disque : P = 2×π×r | A = π×r² (avec π ≈ 3,14)",
            "ATTENTION : périmètre en cm, aire en cm²"
          ],
          "rule": "Aire rectangle = L × l   |   Aire triangle = (b × h) ÷ 2",
          "tip": "🧠 Périmètre = TOUR de la figure. Aire = INTÉRIEUR de la figure.",
          "encouragement": "La géométrie c'est de l'art et des maths réunis. Tu es un artiste du calcul ! 🎨",
          "quizIds": ["m4", "m5"]
        },
        {
          "id": "math-volume",
          "title": "Volume & Contenance",
          "qrCode": "major://lesson/math-volume",
          "emoji": "📦",
          "difficulty": 3,
          "duration": "7 min",
          "summary": "Le volume mesure l'espace occupé par un solide (en cm³ ou m³). La contenance mesure ce qu'un récipient peut contenir (en litres). 1 litre = 1 décimètre cube = 1 dm³.",
          "keyPoints": [
            "Volume du pavé droit = L × l × h",
            "Volume du cube = côté³",
            "1 L = 1 dm³ = 1 000 cm³",
            "1 m³ = 1 000 L",
            "1 cL = 10 mL | 1 dL = 10 cL | 1 L = 10 dL"
          ],
          "rule": "V pavé = L × l × h   |   1 dm³ = 1 L",
          "tip": "🧠 Le litre et le dm³, c'est la même chose ! Utilise ça pour convertir.",
          "encouragement": "Les problèmes de volume font peur ? Pas à toi ! Tu as la formule. 🦁",
          "quizIds": ["m7"]
        },
        {
          "id": "math-decimaux",
          "title": "Nombres Décimaux & Conversions",
          "qrCode": "major://lesson/math-decimaux",
          "emoji": "🔟",
          "difficulty": 1,
          "duration": "5 min",
          "summary": "Les nombres décimaux ont une partie entière et une partie décimale séparées par une virgule. Les conversions de mesures utilisent les puissances de 10.",
          "keyPoints": [
            "1 km = 10 hm = 100 dam = 1 000 m",
            "1 m = 10 dm = 100 cm = 1 000 mm",
            "Multiplier par 10 → déplacer la virgule d'un rang à droite",
            "Diviser par 10 → déplacer la virgule d'un rang à gauche",
            "1 000 × 0,01 = 10"
          ],
          "rule": "×10 → virgule droite | ÷10 → virgule gauche",
          "tip": "🧠 Tableau de conversion : km | hm | dam | m | dm | cm | mm",
          "encouragement": "Les conversions ne te feront plus jamais peur après ça ! Vas-y ! 💥",
          "quizIds": ["m7", "m10"]
        },
        {
          "id": "math-statistiques",
          "title": "Statistiques & Moyenne",
          "qrCode": "major://lesson/math-statistiques",
          "emoji": "📊",
          "difficulty": 2,
          "duration": "5 min",
          "summary": "La moyenne est une valeur représentative d'un groupe de nombres. On l'obtient en divisant la somme de toutes les valeurs par leur nombre total.",
          "keyPoints": [
            "Moyenne = Somme de toutes les valeurs ÷ Nombre de valeurs",
            "Exemple : notes 12, 15, 18, 13, 17 → somme = 75 → 75÷5 = 15",
            "Lire un tableau de données et calculer la moyenne",
            "Fréquence : nombre de fois qu'une valeur apparaît"
          ],
          "rule": "Moyenne = (somme des valeurs) ÷ (nombre de valeurs)",
          "tip": "🧠 Additionne tout d'abord, puis divise ensuite. Dans cet ordre !",
          "encouragement": "La moyenne au concours, tu la calcules maintenant les yeux fermés ! 😎",
          "quizIds": ["m9"]
        }
      ]
    },
    {
      "id": "french",
      "label": "Français",
      "labelAr": "الفرنسية",
      "color": "#38bdf8",
      "gradient": ["#0ea5e9", "#2563eb"],
      "icon": "📖",
      "lessons": [
        {
          "id": "fr-conjugaison-present",
          "title": "Conjugaison — Présent de l'indicatif",
          "qrCode": "major://lesson/fr-conjugaison-present",
          "emoji": "✍️",
          "difficulty": 1,
          "duration": "6 min",
          "summary": "Le présent de l'indicatif exprime une action qui se passe maintenant, une vérité générale ou une habitude. Les terminaisons changent selon le groupe du verbe (1er, 2ème, 3ème groupe).",
          "keyPoints": [
            "1er groupe (-er) : je chant-e, tu chant-es, il chant-e, nous chant-ons, vous chant-ez, ils chant-ent",
            "2ème groupe (-ir) : je fin-is, tu fin-is, il fin-it, nous fin-issons, vous fin-issez, ils fin-issent",
            "Verbes irréguliers à mémoriser : être, avoir, aller, faire, venir, pouvoir, vouloir",
            "ÊTRE : je suis, tu es, il est, nous sommes, vous êtes, ils sont",
            "AVOIR : j'ai, tu as, il a, nous avons, vous avez, ils ont"
          ],
          "rule": "Identifier le groupe → appliquer les terminaisons correctes",
          "tip": "🧠 Le présent de l'indicatif = ce qui se passe MAINTENANT ou TOUJOURS.",
          "encouragement": "La conjugaison c'est comme une recette de cuisine : suis les étapes et c'est parfait ! 🍕",
          "quizIds": ["f21", "f22", "f44", "f53"]
        },
        {
          "id": "fr-conjugaison-passe",
          "title": "Conjugaison — Passé Composé & Imparfait",
          "qrCode": "major://lesson/fr-conjugaison-passe",
          "emoji": "⏮️",
          "difficulty": 2,
          "duration": "8 min",
          "summary": "Le passé composé exprime une action terminée et ponctuelle. L'imparfait exprime une action passée qui dure, se répète ou décrit un état. Les deux temps s'utilisent souvent ensemble.",
          "keyPoints": [
            "Passé composé : avoir/être (auxiliaire au présent) + participe passé",
            "j'ai mangé, tu as couru, il est parti, nous sommes arrivés",
            "Avec ÊTRE : accord du participe passé avec le sujet (elle est partie)",
            "Imparfait : radical + ais, ais, ait, ions, iez, aient",
            "je mangeais, tu courais, il finissait, nous chantions"
          ],
          "rule": "PC = auxiliaire (présent) + PP   |   Imparfait = radical + terminaisons en -ais",
          "tip": "🧠 Passé composé = action finie ('j'ai mangé une pomme'). Imparfait = action qui dure ('je mangeais quand…')",
          "encouragement": "Passé composé ou imparfait ? Tu sais maintenant faire la différence ! 🎓",
          "quizIds": ["f23", "f24", "f43"]
        },
        {
          "id": "fr-conjugaison-futur",
          "title": "Conjugaison — Futur Simple & Conditionnel",
          "qrCode": "major://lesson/fr-conjugaison-futur",
          "emoji": "⏩",
          "difficulty": 2,
          "duration": "6 min",
          "summary": "Le futur simple exprime une action à venir. Le conditionnel présent exprime une action hypothétique ou un souhait poli. Ils ont les mêmes radicaux mais des terminaisons différentes.",
          "keyPoints": [
            "Futur : infinitif + ai, as, a, ons, ez, ont",
            "je mangerai, tu courras, il finira, nous partirons",
            "Verbes irréguliers au futur : être→sera, avoir→aura, aller→ira, faire→fera",
            "Conditionnel : infinitif + ais, ais, ait, ions, iez, aient",
            "je mangerais, tu courrais, il finirait"
          ],
          "rule": "Futur = radical + ai/as/a/ons/ez/ont   |   Conditionnel = radical + ais/ais/ait…",
          "tip": "🧠 Futur = certitude ('je partirai demain'). Conditionnel = hypothèse ('je partirais si…')",
          "encouragement": "Le futur et le conditionnel : deux temps en un seul cours ! Tu es efficace ! ⚡",
          "quizIds": ["f25", "f26"]
        },
        {
          "id": "fr-types-phrases",
          "title": "Types & Formes de Phrases",
          "qrCode": "major://lesson/fr-types-phrases",
          "emoji": "❓",
          "difficulty": 1,
          "duration": "5 min",
          "summary": "Une phrase peut être de 4 types selon son but : déclarative, interrogative, exclamative ou impérative. Elle peut aussi être à la forme affirmative ou négative.",
          "keyPoints": [
            "Déclarative : donne une information. Ex : 'Il fait beau.'",
            "Interrogative : pose une question. Ex : 'Fait-il beau ?'",
            "Exclamative : exprime un sentiment fort. Ex : 'Comme il fait beau !'",
            "Impérative : donne un ordre. Ex : 'Viens ici !'",
            "Forme négative : ne…pas, ne…jamais, ne…plus, ne…rien"
          ],
          "rule": "Type = le but de la phrase | Forme = affirmative ou négative",
          "tip": "🧠 Lis la phrase à voix haute : son ton te dit souvent son type !",
          "encouragement": "Les types de phrases, c'est facile ! Tu les utilises tous les jours sans le savoir. 😄",
          "quizIds": ["f27", "f28", "f45", "f51"]
        },
        {
          "id": "fr-grammaire-fonctions",
          "title": "Grammaire — Fonctions & Analyse",
          "qrCode": "major://lesson/fr-grammaire-fonctions",
          "emoji": "🔍",
          "difficulty": 2,
          "duration": "8 min",
          "summary": "Dans une phrase, chaque mot a une fonction. Identifier le sujet, le verbe, les compléments et les attributs est essentiel pour l'analyse grammaticale au concours.",
          "keyPoints": [
            "Sujet : répond à la question 'Qui est-ce qui ?' ou 'Qu'est-ce qui ?'",
            "Verbe : le mot qui se conjugue (noyau de la phrase)",
            "COD : répond à 'quoi ?' ou 'qui ?' directement après le verbe",
            "COI : répond à 'à quoi/qui ?' ou 'de quoi/qui ?' avec préposition",
            "Attribut du sujet : avec verbe d'état (être, paraître, sembler…)"
          ],
          "rule": "Sujet + Verbe + (COD) + (COI) + (Circonstanciel)",
          "tip": "🧠 Pose les questions dans l'ordre : QUI fait l'action → QUOI → À QUI",
          "encouragement": "L'analyse grammaticale, c'est comme être détective de la langue française ! 🕵️",
          "quizIds": ["f29", "f30", "f31", "f46", "f54"]
        },
        {
          "id": "fr-accord-gn",
          "title": "Accord dans le Groupe Nominal",
          "qrCode": "major://lesson/fr-accord-gn",
          "emoji": "🤝",
          "difficulty": 2,
          "duration": "6 min",
          "summary": "Dans un groupe nominal, le déterminant et l'adjectif s'accordent en genre (masculin/féminin) et en nombre (singulier/pluriel) avec le nom.",
          "keyPoints": [
            "Le chat noir → Les chats noirs (masculin pluriel)",
            "La petite fille → Les petites filles (féminin pluriel)",
            "Féminin : on ajoute généralement -e (grand → grande)",
            "Pluriel : on ajoute généralement -s (petit → petits)",
            "Exceptions : beau → belle, nouveau → nouvelle, vieux → vieille"
          ],
          "rule": "Déterminant + Nom + Adjectif : même genre et même nombre",
          "tip": "🧠 Remplace par 'il/elle' pour trouver le genre, 'ils/elles' pour le nombre.",
          "encouragement": "L'accord du GN, tu ne feras plus jamais de fautes ! C'est promis ! ✨",
          "quizIds": ["f32", "f33", "f50"]
        },
        {
          "id": "fr-homophones",
          "title": "Homophones Grammaticaux",
          "qrCode": "major://lesson/fr-homophones",
          "emoji": "👂",
          "difficulty": 3,
          "duration": "7 min",
          "summary": "Les homophones sont des mots qui se prononcent de la même façon mais s'écrivent différemment. Les confondre est une erreur classique au concours.",
          "keyPoints": [
            "a / à : 'a' = verbe avoir (remplace par 'avait') | 'à' = préposition",
            "est / et : 'est' = verbe être (remplace par 'était') | 'et' = conjonction",
            "on / ont : 'ont' = verbe avoir (remplace par 'avaient') | 'on' = pronom",
            "son / sont : 'sont' = verbe être (remplace par 'étaient') | 'son' = déterminant",
            "se / ce : 'se' devant verbe pronominal | 'ce' = déterminant ou pronom"
          ],
          "rule": "Astuce universelle : remplace par la forme au passé. Si ça marche → verbe conjugué.",
          "tip": "🧠 'Il a faim' → 'Il avait faim' ✓ donc 'a'. 'Il à la maison' → 'Il avait la maison' ✗ donc 'à'.",
          "encouragement": "Les homophones ne te piégeront plus jamais ! Tu as le truc maintenant ! 🔑",
          "quizIds": ["f34", "f35", "f36", "f42", "f48", "f49"]
        },
        {
          "id": "fr-vocabulaire",
          "title": "Vocabulaire — Familles & Champs Lexicaux",
          "qrCode": "major://lesson/fr-vocabulaire",
          "emoji": "📚",
          "difficulty": 1,
          "duration": "5 min",
          "summary": "La famille d'un mot regroupe tous les mots qui ont la même racine. Le champ lexical regroupe tous les mots qui parlent du même thème.",
          "keyPoints": [
            "Famille de 'terre' : enterrer, terrain, terrestre, atterrir",
            "Synonymes : mots de sens proche (rapide = vite = prompt)",
            "Antonymes : mots de sens contraire (grand ≠ petit)",
            "Préfixes : in- (incapable), re- (refaire), dé- (défaire)",
            "Suffixes : -eur (chanteur), -tion (conjugaison), -ment (rapidement)"
          ],
          "rule": "Famille = même RACINE | Champ lexical = même THÈME",
          "tip": "🧠 Pour trouver la famille d'un mot, cherche sa racine latin ou grec.",
          "encouragement": "Plus tu connais de mots, plus tu es puissant en français ! Continue ! 📖",
          "quizIds": ["f37", "f38", "f39", "f47", "f52"]
        },
        {
          "id": "fr-expression-ecrite",
          "title": "Expression Écrite — Types de Textes",
          "qrCode": "major://lesson/fr-expression-ecrite",
          "emoji": "✏️",
          "difficulty": 3,
          "duration": "8 min",
          "summary": "Au concours, tu peux avoir à produire ou analyser différents types de textes. Chaque type a ses propres caractéristiques et son but particulier.",
          "keyPoints": [
            "Texte narratif : raconte une histoire (personnages, lieu, temps, action)",
            "Texte descriptif : décrit un lieu ou une personne (détails sensoriels)",
            "Texte informatif : donne des informations (faits, chiffres, explications)",
            "Texte argumentatif : défend une opinion (arguments + exemples)",
            "Lettre : formule de politesse au début ET à la fin"
          ],
          "rule": "But du texte → type → structure → vocabulaire adapté",
          "tip": "🧠 Avant d'écrire : PLAN (introduction, développement, conclusion) !",
          "encouragement": "Écrire c'est ta super-pouvoir. Entraîne-le et tu brilleras au concours ! ⭐",
          "quizIds": ["f40", "f41", "f55"]
        }
      ]
    },
    {
      "id": "science",
      "label": "Sciences",
      "labelAr": "العلوم الطبيعية",
      "color": "#34d399",
      "gradient": ["#10b981", "#059669"],
      "icon": "🔬",
      "lessons": [
        {
          "id": "sci-digestion",
          "title": "La Nutrition & La Digestion",
          "qrCode": "major://lesson/sci-digestion",
          "emoji": "🥗",
          "difficulty": 1,
          "duration": "6 min",
          "summary": "La digestion transforme les aliments en nutriments que le corps peut absorber. Elle se fait en plusieurs étapes dans l'appareil digestif.",
          "keyPoints": [
            "Chemin des aliments : bouche → œsophage → estomac → intestin grêle → gros intestin",
            "La bouche : mastication + salive (débute la digestion)",
            "L'estomac : digestion chimique avec les sucs gastriques",
            "L'intestin grêle : absorption des nutriments dans le sang",
            "Les aliments se classent en 7 groupes (glucides, lipides, protéines, vitamines…)"
          ],
          "rule": "Digestion = transformation mécanique (mastication) + transformation chimique (sucs digestifs)",
          "tip": "🧠 Retiens l'ordre : bouche → œsophage → estomac → intestin grêle → gros intestin → anus",
          "encouragement": "Tu sais maintenant ce qui se passe dans ton corps quand tu manges ! Fascinant ! 🌟",
          "quizIds": []
        },
        {
          "id": "sci-circulation",
          "title": "La Circulation Sanguine",
          "qrCode": "major://lesson/sci-circulation",
          "emoji": "❤️",
          "difficulty": 2,
          "duration": "6 min",
          "summary": "Le sang circule dans tout le corps grâce au cœur qui est une pompe musculaire. Il transporte l'oxygène et les nutriments vers les organes et ramène le dioxyde de carbone.",
          "keyPoints": [
            "Le cœur a 4 cavités : 2 oreillettes + 2 ventricules",
            "Grande circulation : cœur → corps → cœur (apporte O₂)",
            "Petite circulation : cœur → poumons → cœur (rejette CO₂)",
            "Artères : transportent le sang du cœur | Veines : ramènent au cœur",
            "Sang rouge (artères) = riche en O₂ | Sang bleu/foncé (veines) = pauvre en O₂"
          ],
          "rule": "Cœur → Artères → Organes → Veines → Cœur → Poumons → Cœur",
          "tip": "🧠 Artère = part du cœur (commence par A comme 'aller'). Veine = revient au cœur.",
          "encouragement": "Le cœur bat pour toi toute ta vie. Comprends-le, c'est fascinant ! 💓",
          "quizIds": []
        },
        {
          "id": "sci-respiration",
          "title": "La Respiration",
          "qrCode": "major://lesson/sci-respiration",
          "emoji": "💨",
          "difficulty": 1,
          "duration": "5 min",
          "summary": "La respiration permet d'apporter de l'oxygène au corps et d'éliminer le dioxyde de carbone. Elle se fait grâce aux poumons et au mouvement du diaphragme.",
          "keyPoints": [
            "Inspiration : air entre par nez → trachée → bronches → poumons",
            "Expiration : CO₂ sort des poumons → bronches → trachée → nez/bouche",
            "Les alvéoles pulmonaires : échanges gazeux entre air et sang",
            "Inspiration : diaphragme descend, cage thoracique s'élargit",
            "O₂ passe dans le sang, CO₂ passe dans l'air"
          ],
          "rule": "Inspiration = entrée O₂ | Expiration = sortie CO₂",
          "tip": "🧠 Inspire profondément et pense à ce que font tes poumons. Science en direct !",
          "encouragement": "Tu respires 20 000 fois par jour. Maintenant tu sais pourquoi ! 🫁",
          "quizIds": []
        },
        {
          "id": "sci-reproduction-humaine",
          "title": "La Reproduction Humaine",
          "qrCode": "major://lesson/sci-reproduction-humaine",
          "emoji": "👶",
          "difficulty": 2,
          "duration": "6 min",
          "summary": "La reproduction humaine est sexuée : elle nécessite une cellule reproductrice mâle (spermatozoïde) et une cellule reproductrice femelle (ovule). Leur union forme un embryon.",
          "keyPoints": [
            "Fécondation : union du spermatozoïde et de l'ovule → formation de l'œuf (zygote)",
            "L'embryon se développe dans l'utérus pendant 9 mois",
            "Après 8 semaines, l'embryon devient un fœtus",
            "Le placenta assure les échanges entre la mère et le fœtus",
            "Puberté : période de transformation du corps (fille : 10-13 ans, garçon : 11-14 ans)"
          ],
          "rule": "Fécondation → Œuf → Embryon (0-8 sem) → Fœtus (8 sem - 9 mois) → Naissance",
          "tip": "🧠 9 mois = 3 trimestres. Chaque trimestre apporte des changements importants.",
          "encouragement": "La vie commence par une cellule invisible. La science, c'est magique ! ✨",
          "quizIds": []
        },
        {
          "id": "sci-plantes",
          "title": "Les Plantes — Nutrition & Reproduction",
          "qrCode": "major://lesson/sci-plantes",
          "emoji": "🌿",
          "difficulty": 2,
          "duration": "6 min",
          "summary": "Les plantes fabriquent leur propre nourriture grâce à la photosynthèse. Elles se reproduisent par graines (reproduction sexuée) ou par bouturage, bulbes, stolons (reproduction végétative).",
          "keyPoints": [
            "Photosynthèse : lumière + eau + CO₂ → glucose + O₂",
            "La photosynthèse a lieu dans les feuilles (chlorophylle)",
            "Fleur → fécondation (pollen + ovule) → graine → germination",
            "Reproduction végétative : bouture, bulbe, tubercule, stolon",
            "Les plantes absorbent l'eau et les sels minéraux par les racines"
          ],
          "rule": "CO₂ + H₂O + lumière → glucose + O₂ (Photosynthèse)",
          "tip": "🧠 Sans lumière = pas de photosynthèse = pas de nourriture pour la plante !",
          "encouragement": "Les plantes fabriquent l'oxygène qu'on respire. Sans elles, pas de vie ! 🌍",
          "quizIds": []
        },
        {
          "id": "sci-ecosystemes",
          "title": "Les Êtres Vivants & l'Environnement",
          "qrCode": "major://lesson/sci-ecosystemes",
          "emoji": "🌍",
          "difficulty": 2,
          "duration": "7 min",
          "summary": "Un écosystème est l'ensemble des êtres vivants (biocénose) et leur environnement (biotope) en interaction. Les êtres vivants sont liés entre eux par des chaînes alimentaires.",
          "keyPoints": [
            "Chaîne alimentaire : producteur → consommateur 1 → consommateur 2 → décomposeur",
            "Producteurs = plantes vertes (font la photosynthèse)",
            "Consommateurs : herbivores, carnivores, omnivores",
            "Décomposeurs : bactéries, champignons (recyclent la matière)",
            "Réseau alimentaire = plusieurs chaînes alimentaires liées"
          ],
          "rule": "Plante → Herbivore → Carnivore → Décomposeur",
          "tip": "🧠 Dans une chaîne alimentaire, la flèche signifie 'est mangé par'.",
          "encouragement": "Chaque être vivant a sa place dans la nature. Toi aussi tu en fais partie ! 🦋",
          "quizIds": []
        },
        {
          "id": "sci-matiere",
          "title": "La Matière & ses États",
          "qrCode": "major://lesson/sci-matiere",
          "emoji": "💧",
          "difficulty": 1,
          "duration": "5 min",
          "summary": "La matière peut exister sous 3 états : solide, liquide et gazeux. Elle peut passer d'un état à l'autre par l'effet de la chaleur ou du froid. Ces changements sont réversibles.",
          "keyPoints": [
            "Solide : forme propre et volume propre (glace)",
            "Liquide : pas de forme propre, volume propre (eau)",
            "Gazeux : pas de forme propre, pas de volume propre (vapeur d'eau)",
            "Fusion : solide → liquide (chauffage) | Solidification : liquide → solide (refroidissement)",
            "Vaporisation : liquide → gaz | Condensation : gaz → liquide"
          ],
          "rule": "Chaleur : solide → liquide → gaz | Froid : gaz → liquide → solide",
          "tip": "🧠 L'eau à 0°C gèle (solidification). L'eau à 100°C bout (vaporisation).",
          "encouragement": "La physique-chimie, c'est partout autour de toi ! Observe et tu comprendras ! 👀",
          "quizIds": []
        },
        {
          "id": "sci-terre-eau",
          "title": "La Terre, l'Eau & l'Air",
          "qrCode": "major://lesson/sci-terre-eau",
          "emoji": "🌊",
          "difficulty": 2,
          "duration": "6 min",
          "summary": "L'eau est indispensable à la vie. Elle se trouve partout sur Terre et se transforme en permanence dans le cycle de l'eau. L'air est un mélange de gaz essentiel à la vie.",
          "keyPoints": [
            "Cycle de l'eau : évaporation → condensation → précipitations → ruissellement",
            "Composition de l'air : 78% azote, 21% oxygène, 1% autres gaz",
            "L'air n'est pas visible mais il a une masse et occupe un volume",
            "Pollution de l'eau et de l'air : causes et conséquences",
            "Économiser l'eau : ressource précieuse et limitée"
          ],
          "rule": "Cycle de l'eau : Évaporation → Nuages → Pluie → Rivières → Mer → Évaporation…",
          "tip": "🧠 L'eau fait le tour de la Terre en permanence. Elle ne disparaît jamais !",
          "encouragement": "Protéger l'eau et l'air, c'est protéger la vie sur Terre. Tu peux agir ! 🌱",
          "quizIds": []
        },
        {
          "id": "sci-matiere",
          "title": "La Matière & ses États",
          "qrCode": "major://lesson/sci-matiere",
          "emoji": "💧",
          "difficulty": 1,
          "duration": "5 min",
          "summary": "La matière peut exister sous 3 états : solide, liquide et gazeux. Elle peut passer d'un état à l'autre par l'effet de la chaleur ou du froid. Ces changements sont réversibles.",
          "keyPoints": [
            "Solide : forme propre et volume propre (glace)",
            "Liquide : pas de forme propre, volume propre (eau)",
            "Gazeux : pas de forme propre, pas de volume propre (vapeur d'eau)",
            "Fusion : solide → liquide (chauffage) | Solidification : liquide → solide (refroidissement)",
            "Vaporisation : liquide → gaz | Condensation : gaz → liquide"
          ],
          "rule": "Chaleur : solide → liquide → gaz | Froid : gaz → liquide → solide",
          "tip": "🧠 L'eau à 0°C gèle (solidification). L'eau à 100°C bout (vaporisation).",
          "encouragement": "La physique-chimie, c'est partout autour de toi ! Observe et tu comprendras ! 👀",
          "quizIds": []
        }
      ]
    },

    {
      "id": "arabe",
      "label": "Arabe",
      "labelAr": "اللغة العربية",
      "color": "#06803C",
      "gradient": ["#065f46", "#06803C"],
      "icon": "🕌",
      "isArabic": true,
      "lessons": [
        {
          "id": "ar-grammaire-base",
          "title": "النحو — الفاعل والمفعول به",
          "titleFr": "Grammaire — Sujet et COD",
          "qrCode": "major://lesson/ar-grammaire-base",
          "emoji": "✍️",
          "difficulty": 1,
          "duration": "5 دقائق",
          "summary": "الجملة الفعلية تتكون من فعل وفاعل ومفعول به. الفاعل هو من قام بالفعل، والمفعول به هو من وقع عليه الفعل.",
          "keyPoints": [
            "الفاعل: مرفوع دائماً بالضمة — مثال: جاءَ الطالبُ",
            "المفعول به: منصوب دائماً بالفتحة — مثال: قرأَ الطالبُ الكتابَ",
            "الفعل يتقدم على الفاعل في الجملة الفعلية",
            "يمكن أن تكون الجملة فعلية (فعل+فاعل) أو اسمية (مبتدأ+خبر)"
          ],
          "rule": "الفعل + الفاعل (مرفوع) + المفعول به (منصوب)",
          "tip": "🧠 تذكّر: الفاعل يجيب عن سؤال «مَن فعل؟» والمفعول به يجيب عن «ماذا؟»",
          "encouragement": "إتقان النحو هو مفتاح اللغة العربية. أنت في الطريق الصحيح! 🏆",
          "quizIds": ["ar1", "ar8"]
        },
        {
          "id": "ar-conjugaison",
          "title": "الأفعال — الماضي والمضارع والأمر",
          "titleFr": "Conjugaison arabe — 3 temps",
          "qrCode": "major://lesson/ar-conjugaison",
          "emoji": "⏱️",
          "difficulty": 1,
          "duration": "5 دقائق",
          "summary": "الفعل العربي ثلاثة أنواع: الماضي (حدث انتهى)، المضارع (يحدث الآن أو سيحدث)، الأمر (طلب القيام بالفعل).",
          "keyPoints": [
            "الفعل الماضي: مبني على الفتح — مثال: كَتَبَ، ذَهَبَ",
            "الفعل المضارع: يبدأ بأحد حروف (أ ن ي ت) — مثال: يَكتُبُ، تَذهبُ",
            "فعل الأمر: للطلب المباشر — مثال: اكتُبْ، اذهَبْ",
            "المضارع المجزوم: يُجزم بالسكون — مثال: لم يكتبْ"
          ],
          "rule": "ماضٍ + مضارع + أمر | الماضي مفتوح — المضارع مرفوع — الأمر مجزوم",
          "tip": "🧠 اختبر الزمن: إذا أمكن وضع «أمس» → ماضٍ | «الآن/غداً» → مضارع",
          "encouragement": "الأفعال هي قلب اللغة العربية. كلما تدربت، كلما أتقنت! 💪",
          "quizIds": ["ar3", "ar12"]
        },
        {
          "id": "ar-jamaa",
          "title": "الجمع — سالم وتكسير",
          "titleFr": "Les pluriels en arabe",
          "qrCode": "major://lesson/ar-jamaa",
          "emoji": "📚",
          "difficulty": 2,
          "duration": "6 دقائق",
          "summary": "الجمع في العربية نوعان: جمع سالم (بإضافة لاحقة) وجمع تكسير (بتغيير بنية الكلمة).",
          "keyPoints": [
            "جمع مذكر سالم: يُجمع بـ (ون/ين) — معلم ← معلمون/معلمين",
            "جمع مؤنث سالم: يُجمع بـ (ات) — مدرسة ← مدرسات",
            "جمع التكسير: يتغير فيه بناء المفرد — كتاب ← كتب | قلم ← أقلام",
            "المثنى: يُجمع بـ (ان/ين) — كتاب ← كتابان/كتابين"
          ],
          "rule": "مذكر سالم: + ون/ين | مؤنث سالم: + ات | تكسير: تغيير البنية",
          "tip": "🧠 إذا كانت الكلمة لعاقل مذكر → سالم مذكر | لغير ذلك → راجع التكسير",
          "encouragement": "جمع الكلمات العربية متنوع ورائع. الممارسة تُتقنه! 🌟",
          "quizIds": ["ar2", "ar4", "ar10"]
        },
        {
          "id": "ar-iraab",
          "title": "الإعراب — الحالات الثلاث",
          "titleFr": "Les déclinaisons arabes",
          "qrCode": "major://lesson/ar-iraab",
          "emoji": "🎯",
          "difficulty": 2,
          "duration": "6 دقائق",
          "summary": "الإعراب هو تغيير آخر الكلمة حسب موقعها في الجملة. ثلاث حالات: الرفع، النصب، الجر.",
          "keyPoints": [
            "الرفع بالضمة (ُ): الفاعل، المبتدأ، الخبر — الطالبُ مجتهدٌ",
            "النصب بالفتحة (َ): المفعول به، اسم إن — إن الطالبَ مجتهدٌ",
            "الجر بالكسرة (ِ): بعد حروف الجر — في البيتِ، إلى المدرسةِ",
            "حروف الجر: في، على، من، إلى، عن، الباء، اللام، الكاف"
          ],
          "rule": "رفع (ُ) = فاعل/مبتدأ | نصب (َ) = مفعول/اسم إن | جر (ِ) = بعد حرف جر",
          "tip": "🧠 اسأل: «من فعل؟» → رفع | «ماذا؟» → نصب | «بعد أين/من/إلى؟» → جر",
          "encouragement": "الإعراب هو سر الفصاحة! من أتقنه فتحت له أبواب العربية. 🗝️",
          "quizIds": ["ar5", "ar7", "ar14"]
        },
        {
          "id": "ar-naat",
          "title": "النعت والضمائر",
          "titleFr": "Adjectifs et pronoms arabes",
          "qrCode": "major://lesson/ar-naat",
          "emoji": "💡",
          "difficulty": 2,
          "duration": "5 دقائق",
          "summary": "النعت (الصفة) يصف الاسم قبله ويتبعه في كل شيء. الضمائر منفصلة ومتصلة.",
          "keyPoints": [
            "النعت يتبع المنعوت في: الإعراب، التعريف/التنكير، الجنس، العدد",
            "مثال: قرأتُ كتاباً مفيداً (كلاهما نكرة منصوبة)",
            "الضمير المنفصل: أنا، أنتَ، هو، هي، نحن، أنتم، هم",
            "الضمير المتصل: الهاء في (كتابه)، الكاف في (معلمك)، الياء في (بيتي)"
          ],
          "rule": "النعت يتبع المنعوت | الضمير المتصل يلتصق بالكلمة",
          "tip": "🧠 الضمير المتصل يختصر الكلام: «كتاب + هو» ← «كتابه»",
          "encouragement": "أنت تتقدم بشكل رائع في اللغة العربية! استمر! 🐪✨",
          "quizIds": ["ar9", "ar13"]
        }
      ]
    },

    {
      "id": "histoire_geo",
      "label": "Histoire-Géo",
      "labelAr": "التاريخ والجغرافيا",
      "color": "#8b5cf6",
      "gradient": ["#6d28d9", "#8b5cf6"],
      "icon": "🌍",
      "isArabic": true,
      "lessons": [
        {
          "id": "hg-mauritanie",
          "title": "موريتانيا — الجغرافيا والتاريخ",
          "titleFr": "Mauritanie — Géographie & Histoire",
          "qrCode": "major://lesson/hg-mauritanie",
          "emoji": "🇲🇷",
          "difficulty": 1,
          "duration": "6 دقائق",
          "summary": "موريتانيا دولة في شمال غرب أفريقيا، عاصمتها نواكشوط. نالت استقلالها عام 1960. تطل على المحيط الأطلسي غرباً.",
          "keyPoints": [
            "العاصمة: نواكشوط | ثاني مدينة: نواذيبو (ميناء رئيسي)",
            "الاستقلال: 28 نوفمبر 1960 عن فرنسا",
            "الحدود: المغرب والجزائر شمالاً، مالي شرقاً، السنغال جنوباً",
            "المناخ: صحراوي في معظم البلاد، شبه جاف في الجنوب",
            "الموارد: خام الحديد، الثروة السمكية، النفط"
          ],
          "rule": "موريتانيا = شمال غرب أفريقيا | الاستقلال 1960 | عاصمة نواكشوط",
          "tip": "🧠 تذكّر: نواكشوط (العاصمة) + نواذيبو (الميناء) = المدينتان الرئيسيتان",
          "encouragement": "معرفة وطنك خطوة أولى نحو بناء مستقبله! 🇲🇷",
          "quizIds": ["hg1", "hg2", "hg5"]
        },
        {
          "id": "hg-afrique",
          "title": "القارة الأفريقية",
          "titleFr": "Le continent africain",
          "qrCode": "major://lesson/hg-afrique",
          "emoji": "🌍",
          "difficulty": 1,
          "duration": "5 دقائق",
          "summary": "أفريقيا ثاني أكبر قارات العالم. تتميز بتنوع مناخاتها وأنهارها وشعوبها. تقع موريتانيا في شمالها الغربي.",
          "keyPoints": [
            "أفريقيا: 54 دولة، أكثر من مليار نسمة",
            "أطول نهر: النيل (6650 كم) | أكبر صحراء: الصحراء الكبرى",
            "أعلى جبل: كليمنجارو في تنزانيا (5895 م)",
            "الأنهار الكبرى: النيل، الكونغو، النيجر، السنغال",
            "نهر السنغال يفصل موريتانيا عن السنغال"
          ],
          "rule": "أفريقيا = 54 دولة | النيل أطول نهر | الصحراء الكبرى أكبر صحراء",
          "tip": "🧠 تذكّر الأنهار الكبرى: النيل (شرق) — النيجر (غرب) — الكونغو (وسط)",
          "encouragement": "أفريقيا قارتنا الجميلة. تعرّف عليها وافتخر بها! 🌟",
          "quizIds": ["hg6", "hg8", "hg10"]
        },
        {
          "id": "hg-monde",
          "title": "قارات العالم",
          "titleFr": "Les continents du monde",
          "qrCode": "major://lesson/hg-monde",
          "emoji": "🌐",
          "difficulty": 1,
          "duration": "5 دقائق",
          "summary": "يتكون العالم من 7 قارات و5 محيطات. آسيا أكبر القارات. المحيط الهادئ أكبر المحيطات.",
          "keyPoints": [
            "القارات السبع: آسيا، أفريقيا، أمريكا الشمالية، أمريكا الجنوبية، أنتاركتيكا، أوروبا، أستراليا",
            "أكبر قارة: آسيا | أصغر قارة: أستراليا",
            "المحيطات الخمسة: الهادئ، الأطلسي، الهندي، القطبي الشمالي، القطبي الجنوبي",
            "أكبر محيط: الهادئ | موريتانيا على المحيط الأطلسي"
          ],
          "rule": "7 قارات + 5 محيطات | آسيا أكبر قارة | الهادئ أكبر محيط",
          "tip": "🧠 قاعدة للحفظ: «أفريقيا وآسيا وأمريكتان وأوروبا وأستراليا وأنتاركتيكا»",
          "encouragement": "العالم واسع ورائع. الجغرافيا تفتح عينيك عليه! 🌏",
          "quizIds": ["hg6", "hg10"]
        },
        {
          "id": "hg-histoire-ao",
          "title": "الإمبراطوريات الأفريقية القديمة",
          "titleFr": "Les grands empires africains",
          "qrCode": "major://lesson/hg-histoire-ao",
          "emoji": "👑",
          "difficulty": 2,
          "duration": "6 دقائق",
          "summary": "قامت في غرب أفريقيا إمبراطوريات عظيمة قبل الاستعمار الأوروبي: غانا، مالي، سنغاي.",
          "keyPoints": [
            "إمبراطورية غانا (ق4-ق13): أول الإمبراطوريات الكبرى في غرب أفريقيا",
            "إمبراطورية مالي (ق13-ق16): شهيرة بملكها مانسا موسى وثروته الأسطورية",
            "إمبراطورية سنغاي (ق15-ق16): أكبر إمبراطوريات غرب أفريقيا",
            "مدينة تمبكتو: مركز علمي وتجاري مشهور",
            "موريتانيا كانت طريقاً للتجارة الصحراوية"
          ],
          "rule": "غانا → مالي → سنغاي | إمبراطوريات غرب أفريقيا قبل الاستعمار",
          "tip": "🧠 ترتيب زمني: غانا أقدم ← مالي ← سنغاي الأحدث",
          "encouragement": "أجدادنا بنوا حضارات عظيمة. تاريخنا مصدر فخر! 👑",
          "quizIds": ["hg12"]
        }
      ]
    },

    {
      "id": "islamique",
      "label": "Islamique",
      "labelAr": "التربية الإسلامية",
      "color": "#059669",
      "gradient": ["#047857", "#059669"],
      "icon": "☪️",
      "isArabic": true,
      "lessons": [
        {
          "id": "is-arkane-islam",
          "title": "أركان الإسلام الخمسة",
          "titleFr": "Les 5 piliers de l'Islam",
          "qrCode": "major://lesson/is-arkane-islam",
          "emoji": "☪️",
          "difficulty": 1,
          "duration": "5 دقائق",
          "summary": "بُني الإسلام على خمسة أركان. هي الأسس التي يقوم عليها دين المسلم وتُعبّر عن علاقته بربه.",
          "keyPoints": [
            "1. شهادة أن لا إله إلا الله وأن محمداً رسول الله",
            "2. إقامة الصلاة — خمس صلوات في اليوم والليلة",
            "3. إيتاء الزكاة — جزء من المال للفقراء ومن يستحق",
            "4. صوم رمضان — شهر كامل من الفجر إلى المغرب",
            "5. الحج إلى مكة المكرمة — مرة في العمر لمن استطاع"
          ],
          "rule": "شهادة ← صلاة ← زكاة ← صوم ← حج",
          "tip": "🧠 حفظ الترتيب: «شَصَزَصَحَ» — شهادة، صلاة، زكاة، صوم، حج",
          "encouragement": "أركان الإسلام هي طريقك للجنة. تعلّمها وطبّقها! 🌟",
          "quizIds": ["is1", "is2", "is3", "is4", "is5"]
        },
        {
          "id": "is-arkane-iman",
          "title": "أركان الإيمان الستة",
          "titleFr": "Les 6 piliers de la Foi",
          "qrCode": "major://lesson/is-arkane-iman",
          "emoji": "💎",
          "difficulty": 1,
          "duration": "5 دقائق",
          "summary": "الإيمان يشمل ستة أركان: الإيمان بالله وملائكته وكتبه ورسله واليوم الآخر والقدر.",
          "keyPoints": [
            "1. الإيمان بالله: الخالق الواحد لا شريك له",
            "2. الإيمان بالملائكة: خُلقوا من نور، يطيعون الله دائماً",
            "3. الإيمان بالكتب: التوراة، الإنجيل، الزبور، القرآن الكريم",
            "4. الإيمان بالرسل: من آدم إلى محمد ﷺ خاتم الأنبياء",
            "5. الإيمان باليوم الآخر: الحساب والجزاء",
            "6. الإيمان بالقدر: خيره وشره من الله"
          ],
          "rule": "الله ← الملائكة ← الكتب ← الرسل ← اليوم الآخر ← القدر",
          "tip": "🧠 «أملكرق» — أركان الإيمان الستة بالترتيب",
          "encouragement": "الإيمان الصحيح يُنير القلب ويُهدي إلى الصراط المستقيم! ✨",
          "quizIds": ["is7", "is8"]
        },
        {
          "id": "is-salat",
          "title": "الصلاة — أحكام وأوقات",
          "titleFr": "La prière — règles et horaires",
          "qrCode": "major://lesson/is-salat",
          "emoji": "🕌",
          "difficulty": 1,
          "duration": "5 دقائق",
          "summary": "الصلاة عمود الدين وثاني أركان الإسلام. خمس صلوات في اليوم لها أوقات محددة وعدد ركعات.",
          "keyPoints": [
            "الفجر: ركعتان — من طلوع الفجر إلى شروق الشمس",
            "الظهر: أربع ركعات — بعد زوال الشمس",
            "العصر: أربع ركعات — بعد الظهر إلى قبيل الغروب",
            "المغرب: ثلاث ركعات — بعد غروب الشمس مباشرة",
            "العشاء: أربع ركعات — بعد اختفاء الشفق الأحمر"
          ],
          "rule": "فجر(2) + ظهر(4) + عصر(4) + مغرب(3) + عشاء(4) = 17 ركعة",
          "tip": "🧠 المجموع 17 ركعة يومياً: 2+4+4+3+4 = 17",
          "encouragement": "الصلاة نور في القلب وراحة للنفس. حافظ عليها! 🤲",
          "quizIds": ["is2", "is5", "is11"]
        },
        {
          "id": "is-akhlaq",
          "title": "الأخلاق الإسلامية",
          "titleFr": "Les valeurs morales islamiques",
          "qrCode": "major://lesson/is-akhlaq",
          "emoji": "🌸",
          "difficulty": 1,
          "duration": "5 دقائق",
          "summary": "الإسلام دين الأخلاق الحسنة. قال النبي ﷺ: «إنما بُعثت لأتمم مكارم الأخلاق». الأخلاق الحسنة تُقرّب من الله والناس.",
          "keyPoints": [
            "الصدق: قول الحق دائماً، الكذب حرام",
            "بر الوالدين: طاعتهما والإحسان إليهما",
            "الأمانة: رد الأمانات، عدم الخيانة",
            "التعاون: مساعدة المحتاج والجار",
            "احترام الكبير والرحمة بالصغير"
          ],
          "rule": "صدق + أمانة + بر الوالدين + تعاون = أخلاق المسلم",
          "tip": "🧠 النبي ﷺ قال: «المسلم من سلم المسلمون من لسانه ويده»",
          "encouragement": "الأخلاق الحسنة تجعلك محبوباً عند الله والناس! كن القدوة! 🌟",
          "quizIds": ["is10", "is13"]
        }
      ]
    },

    // ── Cahier Major 6AF arabe : الرياضيات (QR math6-u01…u31) ──
    {
      "id": "math6-ar",
      "label": "Mathématiques 6AF",
      "labelAr": "الرياضيات",
      "color": "#fb923c",
      "gradient": ["#f59e0b", "#fb923c"],
      "icon": "📐",
      "isArabic": true,
      "lessons": [...MATH6_LESSONS_1, ...MATH6_LESSONS_2]
    },
    // ── Cahier Major 6AF arabe : العلوم الطبيعية (QR sci6-u1…u6) ──
    {
      "id": "sci6-ar",
      "label": "Sciences naturelles 6AF",
      "labelAr": "العلوم الطبيعية",
      "color": "#34d399",
      "gradient": ["#10b981", "#34d399"],
      "icon": "🔬",
      "isArabic": true,
      "lessons": SCI6_LESSONS
    },
    // ── Cahier Major arabe-islamique 6AF : اللغة العربية (QR ar6-u01…u18) ──
    {
      "id": "ar6",
      "label": "Arabe 6AF",
      "labelAr": "اللغة العربية",
      "color": "#7c3aed",
      "gradient": ["#5b21b6", "#7c3aed"],
      "icon": "📘",
      "isArabic": true,
      "lessons": [...AR6_LESSONS_1, ...AR6_LESSONS_2]
    },
    // ── Cahier Major arabe-islamique 6AF : التربية الإسلامية (QR isl6-u1…u8) ──
    {
      "id": "isl6",
      "label": "Islamique 6AF",
      "labelAr": "التربية الإسلامية",
      "color": "#0d9488",
      "gradient": ["#0f766e", "#14b8a6"],
      "icon": "☪️",
      "isArabic": true,
      "lessons": ISL6_LESSONS
    },
    // ── Cahier Major histoire-géo-civique 6AF : التاريخ والجغرافيا (QR hg6-u01…u18) ──
    {
      "id": "hg6",
      "label": "Histoire-Géo 6AF",
      "labelAr": "التاريخ والجغرافيا",
      "color": "#b45309",
      "gradient": ["#92400e", "#d97706"],
      "icon": "🏰",
      "isArabic": true,
      "lessons": [...HG6_LESSONS_1, ...HG6_LESSONS_2]
    },
    // ── Cahier Major histoire-géo-civique 6AF : التربية المدنية (QR civ6-u1…u7) ──
    {
      "id": "civ6",
      "label": "Éducation civique 6AF",
      "labelAr": "التربية المدنية",
      "color": "#0f7b3a",
      "gradient": ["#064e2b", "#0f7b3a"],
      "icon": "🤝",
      "isArabic": true,
      "lessons": CIV6_LESSONS
    }
  ]
}
;

// Exercices QCM — Concours 6AF Mauritanie
// Chaque exercice : id, question, options[], answer (index), explanation, difficulty (1-3)

export const EXERCISES = {
  math: [
    {
      id: 'm1',
      question: 'Quel est le résultat de 3/4 + 1/4 ?',
      options: ['1/2', '4/8', '1', '2/4'],
      answer: 2,
      explanation: '3/4 + 1/4 = 4/4 = 1. Quand les dénominateurs sont égaux, on additionne les numérateurs.',
      difficulty: 1,
    },
    {
      id: 'm2',
      question: 'Combien vaut 5/8 de 40 ?',
      options: ['20', '25', '15', '30'],
      answer: 1,
      explanation: '5/8 × 40 = (5 × 40) ÷ 8 = 200 ÷ 8 = 25.',
      difficulty: 2,
    },
    {
      id: 'm3',
      question: 'Quel nombre est compris entre 3/4 et 1 ?',
      options: ['1/2', '7/8', '5/4', '2/4'],
      answer: 1,
      explanation: '3/4 = 0,75 et 1 = 1,00. La fraction 7/8 = 0,875 est bien entre les deux.',
      difficulty: 2,
    },
    {
      id: 'm4',
      question: 'Quelle est l\'aire d\'un rectangle de longueur 8 cm et de largeur 5 cm ?',
      options: ['26 cm²', '40 cm²', '13 cm²', '80 cm²'],
      answer: 1,
      explanation: 'Aire = longueur × largeur = 8 × 5 = 40 cm².',
      difficulty: 1,
    },
    {
      id: 'm5',
      question: 'Quel est le périmètre d\'un carré de côté 6 cm ?',
      options: ['12 cm', '24 cm', '36 cm', '18 cm'],
      answer: 1,
      explanation: 'Périmètre du carré = 4 × côté = 4 × 6 = 24 cm.',
      difficulty: 1,
    },
    {
      id: 'm6',
      question: 'Ahmed a 120 billes. Il en donne 2/5 à son ami. Combien lui reste-t-il ?',
      options: ['48', '72', '60', '80'],
      answer: 1,
      explanation: '2/5 de 120 = 48. Il reste 120 - 48 = 72 billes.',
      difficulty: 2,
    },
    {
      id: 'm7',
      question: 'Combien y a-t-il de centimètres dans 2,5 mètres ?',
      options: ['25 cm', '2 500 cm', '250 cm', '0,25 cm'],
      answer: 2,
      explanation: '1 mètre = 100 cm. Donc 2,5 m = 2,5 × 100 = 250 cm.',
      difficulty: 1,
    },
    {
      id: 'm8',
      question: 'Quel est le PGCD de 12 et 18 ?',
      options: ['3', '6', '9', '12'],
      answer: 1,
      explanation: 'Les diviseurs de 12 : 1,2,3,4,6,12. Les diviseurs de 18 : 1,2,3,6,9,18. Le plus grand commun est 6.',
      difficulty: 2,
    },
    {
      id: 'm9',
      question: 'Un robinet remplit un réservoir de 240 litres en 6 heures. Combien de litres par heure ?',
      options: ['30 L/h', '40 L/h', '60 L/h', '48 L/h'],
      answer: 1,
      explanation: '240 ÷ 6 = 40 litres par heure.',
      difficulty: 2,
    },
    {
      id: 'm10',
      question: 'Quel est le résultat de 1 000 × 0,01 ?',
      options: ['100', '10', '1', '0,1'],
      answer: 1,
      explanation: '1 000 × 0,01 = 1 000 × 1/100 = 10.',
      difficulty: 2,
    },
    {
      id: 'm11',
      question: 'La somme des angles d\'un triangle est :',
      options: ['90°', '360°', '180°', '270°'],
      answer: 2,
      explanation: 'La somme des angles intérieurs d\'un triangle est toujours égale à 180°.',
      difficulty: 1,
    },
    {
      id: 'm12',
      question: 'Quel est le prix d\'un article après une réduction de 20% sur 150 DH ?',
      options: ['130 DH', '120 DH', '110 DH', '125 DH'],
      answer: 1,
      explanation: '20% de 150 = 30 DH. Prix réduit = 150 - 30 = 120 DH.',
      difficulty: 3,
    },
    {
      id: 'm13',
      question: 'Écris en chiffres : deux millions trois cent mille cinquante.',
      options: ['2 300 050', '2 030 050', '2 300 500', '23 000 050'],
      answer: 0,
      explanation: 'Deux millions = 2 000 000 + trois cent mille = 300 000 + cinquante = 50. Total : 2 300 050.',
      difficulty: 2,
    },
    {
      id: 'm14',
      question: 'Quelle fraction est équivalente à 6/9 ?',
      options: ['3/6', '2/3', '4/6', '1/3'],
      answer: 1,
      explanation: '6/9 : on divise numérateur et dénominateur par 3 → 6÷3 / 9÷3 = 2/3.',
      difficulty: 1,
    },
    {
      id: 'm15',
      question: 'Un train parcourt 360 km en 3 heures. Quelle est sa vitesse moyenne ?',
      options: ['90 km/h', '120 km/h', '100 km/h', '180 km/h'],
      answer: 1,
      explanation: 'Vitesse = distance ÷ temps = 360 ÷ 3 = 120 km/h.',
      difficulty: 2,
    },
    {
      id: 'm16',
      question: 'Quel est le volume d\'un cube de côté 3 cm ?',
      options: ['9 cm³', '18 cm³', '27 cm³', '12 cm³'],
      answer: 2,
      explanation: 'Volume du cube = côté³ = 3 × 3 × 3 = 27 cm³.',
      difficulty: 2,
    },
    {
      id: 'm17',
      question: '3/4 est-il supérieur ou inférieur à 2/3 ?',
      options: ['Inférieur', 'Égal', 'Supérieur', 'On ne peut pas comparer'],
      answer: 2,
      explanation: '3/4 = 9/12 et 2/3 = 8/12. Donc 3/4 > 2/3.',
      difficulty: 2,
    },
    {
      id: 'm18',
      question: 'Combien de minutes y a-t-il dans 2h 45min ?',
      options: ['145 min', '165 min', '125 min', '155 min'],
      answer: 1,
      explanation: '2h = 120 min. 120 + 45 = 165 minutes.',
      difficulty: 1,
    },
    {
      id: 'm19',
      question: 'Quel est le résultat de 7,2 × 100 ?',
      options: ['72', '0,072', '720', '7200'],
      answer: 2,
      explanation: 'Multiplier par 100 : on déplace la virgule de 2 rangs vers la droite. 7,2 × 100 = 720.',
      difficulty: 1,
    },
    {
      id: 'm20',
      question: 'Dans une classe de 30 élèves, 12 sont des filles. Quel pourcentage sont des garçons ?',
      options: ['40%', '60%', '55%', '45%'],
      answer: 1,
      explanation: 'Garçons = 30 - 12 = 18. Pourcentage = (18 ÷ 30) × 100 = 60%.',
      difficulty: 3,
    },
  ],

  french: [
    {
      id: 'f1',
      question: 'Quelle est la nature du mot souligné : "Le petit chat dort."  (petit)',
      options: ['Nom', 'Verbe', 'Adjectif qualificatif', 'Adverbe'],
      answer: 2,
      explanation: '"Petit" qualifie le nom "chat". C\'est un adjectif qualificatif épithète.',
      difficulty: 1,
    },
    {
      id: 'f2',
      question: 'Conjuguez "finir" à la 3ème personne du pluriel au présent :',
      options: ['Ils finissaient', 'Ils finissent', 'Ils finiront', 'Ils ont fini'],
      answer: 1,
      explanation: 'Finir est un verbe du 2ème groupe. Au présent : je finis, tu finis, il finit, nous finissons, vous finissez, ils finissent.',
      difficulty: 1,
    },
    {
      id: 'f3',
      question: 'Quel est le féminin de "beau" ?',
      options: ['Beaute', 'Belle', 'Bel', 'Beaux'],
      answer: 1,
      explanation: 'Beau → Belle au féminin. (Bel est utilisé devant une voyelle : un bel arbre.)',
      difficulty: 1,
    },
    {
      id: 'f4',
      question: 'Dans "Les enfants mangent des pommes.", quel est le COD ?',
      options: ['Les enfants', 'mangent', 'des pommes', 'Il n\'y en a pas'],
      answer: 2,
      explanation: '"Des pommes" répond à la question "mangent quoi ?". C\'est le complément d\'objet direct.',
      difficulty: 2,
    },
    {
      id: 'f5',
      question: 'Quel est le pluriel de "cheval" ?',
      options: ['Chevals', 'Chevales', 'Chevaux', 'Cheveaux'],
      answer: 2,
      explanation: 'Les noms en -al font leur pluriel en -aux : cheval → chevaux.',
      difficulty: 1,
    },
    {
      id: 'f6',
      question: 'Conjuguez "aller" au futur simple, 1ère personne du singulier :',
      options: ['Je vais', 'J\'allais', 'J\'irai', 'Je suis allé'],
      answer: 2,
      explanation: 'Aller est un verbe irrégulier. Au futur : j\'irai, tu iras, il ira, nous irons, vous irez, ils iront.',
      difficulty: 2,
    },
    {
      id: 'f7',
      question: 'Quelle est la fonction du mot souligné : "Marie chante bien." (Marie)',
      options: ['COD', 'Sujet', 'Attribut du sujet', 'Complément circonstanciel'],
      answer: 1,
      explanation: '"Marie" est celui qui fait l\'action de chanter. C\'est le sujet du verbe.',
      difficulty: 1,
    },
    {
      id: 'f8',
      question: 'Quel mot est un synonyme de "rapide" ?',
      options: ['Lent', 'Vite', 'Véloce', 'Lourd'],
      answer: 2,
      explanation: '"Véloce" signifie qui se déplace rapidement. C\'est bien un synonyme de "rapide".',
      difficulty: 2,
    },
    {
      id: 'f9',
      question: 'Choisissez la bonne orthographe :',
      options: ['Il c\'est blessé.', 'Il s\'est blessé.', 'Il ses blessé.', 'Il ce blessé.'],
      answer: 1,
      explanation: '"S\'est" = pronom réfléchi "se" + auxiliaire "être". On ne confond pas avec "c\'est" (présentatif).',
      difficulty: 2,
    },
    {
      id: 'f10',
      question: 'Quel est l\'antonyme (contraire) de "courageux" ?',
      options: ['Brave', 'Vaillant', 'Peureux', 'Fort'],
      answer: 2,
      explanation: '"Peureux" signifie qui a peur, qui manque de courage. C\'est le contraire de courageux.',
      difficulty: 1,
    },
    {
      id: 'f11',
      question: 'Dans "Elle mange lentement.", "lentement" est :',
      options: ['Un adjectif', 'Un adverbe', 'Un nom', 'Un verbe'],
      answer: 1,
      explanation: '"Lentement" modifie le verbe "mange". C\'est un adverbe de manière.',
      difficulty: 2,
    },
    {
      id: 'f12',
      question: 'Mettez au passé composé : "Il part tôt."',
      options: ['Il partait tôt.', 'Il est parti tôt.', 'Il a parti tôt.', 'Il sera parti tôt.'],
      answer: 1,
      explanation: 'Partir se conjugue avec l\'auxiliaire "être" au passé composé : il est parti.',
      difficulty: 2,
    },
    {
      id: 'f13',
      question: 'Quel est le genre du nom "la fourmi" ?',
      options: ['Masculin', 'Féminin', 'Neutre', 'Les deux'],
      answer: 1,
      explanation: '"La fourmi" est précédé de l\'article "la", c\'est donc un nom féminin.',
      difficulty: 1,
    },
    {
      id: 'f14',
      question: 'Quelle phrase est à la forme négative ?',
      options: [
        'Il mange une pomme.',
        'Il ne mange pas de pomme.',
        'Mange-t-il une pomme ?',
        'Qu\'il mange une pomme !',
      ],
      answer: 1,
      explanation: 'La forme négative utilise "ne...pas". "Il ne mange pas de pomme" est bien à la forme négative.',
      difficulty: 1,
    },
    {
      id: 'f15',
      question: 'Complétez : "Les oiseaux ___ dans le ciel." (voler, présent)',
      options: ['vole', 'volent', 'volons', 'volez'],
      answer: 1,
      explanation: 'Le sujet "les oiseaux" est à la 3ème personne du pluriel. Voler → ils volent.',
      difficulty: 1,
    },
    {
      id: 'f16',
      question: 'Quel mot s\'écrit avec une majuscule obligatoire ?',
      options: ['le chien', 'Paris', 'un livre', 'courir'],
      answer: 1,
      explanation: 'Les noms propres (villes, personnes, pays...) s\'écrivent avec une majuscule. Paris est une ville.',
      difficulty: 1,
    },
    {
      id: 'f17',
      question: '"Nous avons mangé des fruits." → Quel est le temps de cette phrase ?',
      options: ['Présent', 'Imparfait', 'Passé composé', 'Futur simple'],
      answer: 2,
      explanation: '"Avons mangé" = auxiliaire avoir au présent + participe passé. C\'est le passé composé.',
      difficulty: 1,
    },
    {
      id: 'f18',
      question: 'Quelle est la bonne ponctuation pour une question ?',
      options: ['Le point .', 'Le point d\'exclamation !', 'Le point d\'interrogation ?', 'La virgule ,'],
      answer: 2,
      explanation: 'Une phrase interrogative se termine par un point d\'interrogation (?).',
      difficulty: 1,
    },
    {
      id: 'f19',
      question: 'Quel est le radical du verbe "chanter" ?',
      options: ['chant-', 'chanter-', '-er', 'chantons'],
      answer: 0,
      explanation: 'Le radical est la partie qui reste quand on enlève la terminaison. Chanter → chant (radical) + -er (terminaison).',
      difficulty: 2,
    },
    {
      id: 'f20',
      question: 'Quel pronom remplace "les élèves" dans "Les élèves lisent le texte." ?',
      options: ['Il', 'Elle', 'Ils', 'Elles'],
      answer: 2,
      explanation: '"Les élèves" est un groupe masculin pluriel (ou mixte). On le remplace par "Ils".',
      difficulty: 1,
    },
    {
      id: 'f21',
      question: 'Conjuguez "être" à la 2e personne du pluriel au présent :',
      options: ['Vous êtes', 'Vous seront', 'Vous étiez', 'Vous seras'],
      answer: 0,
      explanation: 'Au présent de l\'indicatif : je suis, tu es, il est, nous sommes, vous êtes, ils sont.',
      difficulty: 1,
    },
    {
      id: 'f22',
      question: 'Conjuguez "avoir" à la 3e personne du singulier au présent :',
      options: ['Il a', 'Il as', 'Il ont', 'Il avons'],
      answer: 0,
      explanation: 'Avoir au présent : j\'ai, tu as, il/elle a, nous avons, vous avez, ils/elles ont.',
      difficulty: 1,
    },
    {
      id: 'f23',
      question: 'Quelle phrase est au passé composé ?',
      options: ['Nous chantons.', 'Nous avons chanté.', 'Nous chantions.', 'Nous chanterons.'],
      answer: 1,
      explanation: 'Le passé composé = auxiliaire (avoir ou être) au présent + participe passé.',
      difficulty: 1,
    },
    {
      id: 'f24',
      question: 'Quelle phrase est à l\'imparfait ?',
      options: ['Il finit son devoir.', 'Il finissait son devoir.', 'Il a fini son devoir.', 'Il finira son devoir.'],
      answer: 1,
      explanation: 'L\'imparfait décrit une action passée qui dure ou se répète : finissait (radical + terminaisons en -ais).',
      difficulty: 2,
    },
    {
      id: 'f25',
      question: 'Conjuguez "manger" au futur simple, 3e personne du pluriel :',
      options: ['Ils mangent', 'Ils mangeront', 'Ils mangeaient', 'Ils ont mangé'],
      answer: 1,
      explanation: 'Futur du 1er groupe : infinitif + terminaisons. Manger → ils mangeront.',
      difficulty: 2,
    },
    {
      id: 'f26',
      question: 'Quelle phrase est au conditionnel présent ?',
      options: ['Je voudrais un cahier.', 'Je veux un cahier.', 'J\'ai voulu un cahier.', 'Je voulais un cahier.'],
      answer: 0,
      explanation: 'Le conditionnel exprime un souhait ou une hypothèse : je voudrais (vouloir au conditionnel).',
      difficulty: 2,
    },
    {
      id: 'f27',
      question: 'Quel est le type de la phrase : « Comme il fait chaud ! »',
      options: ['Déclarative', 'Interrogative', 'Exclamative', 'Impérative'],
      answer: 2,
      explanation: 'Une phrase exclamative exprime une émotion forte et se termine souvent par « ! ».',
      difficulty: 1,
    },
    {
      id: 'f28',
      question: 'Quel est le type de la phrase : « Ouvre la fenêtre. »',
      options: ['Déclarative', 'Interrogative', 'Exclamative', 'Impérative'],
      answer: 3,
      explanation: 'L\'impératif donne un ordre ou une instruction. « Ouvre » est à l\'impératif.',
      difficulty: 1,
    },
    {
      id: 'f29',
      question: 'Dans « Le professeur explique la leçon », quelle est la fonction de « Le professeur » ?',
      options: ['COD', 'Sujet', 'COI', 'Attribut du sujet'],
      answer: 1,
      explanation: '« Le professeur » répond à « Qui explique ? » — c\'est le sujet du verbe « explique ».',
      difficulty: 1,
    },
    {
      id: 'f30',
      question: 'Dans « Elle écrit une lettre », quel est le COD ?',
      options: ['Elle', 'écrit', 'une lettre', 'à son ami'],
      answer: 2,
      explanation: '« Une lettre » répond à « écrit quoi ? » — complément d\'objet direct.',
      difficulty: 2,
    },
    {
      id: 'f31',
      question: 'Dans « Il pense à son examen », quelle est la fonction de « à son examen » ?',
      options: ['COD', 'Sujet', 'Complément circonstanciel de lieu', 'COI'],
      answer: 3,
      explanation: '« Penser à » : le complément introduit par « à » est un COI (répond à « à quoi ? »).',
      difficulty: 2,
    },
    {
      id: 'f32',
      question: 'Accorde l\'adjectif : « une maison ___ » (grand)',
      options: ['grand', 'grande', 'grands', 'grandes'],
      answer: 1,
      explanation: '« Maison » est féminin singulier → l\'adjectif s\'accorde : grande.',
      difficulty: 1,
    },
    {
      id: 'f33',
      question: 'Accorde : « des chats ___ » (noir)',
      options: ['noir', 'noire', 'noirs', 'noires'],
      answer: 2,
      explanation: '« Chats » est masculin pluriel → noirs.',
      difficulty: 1,
    },
    {
      id: 'f34',
      question: 'Complétez avec a ou à : « Il ___ faim. »',
      options: ['a', 'à', 'as', 'as'],
      answer: 0,
      explanation: '« Avoir faim » : le verbe avoir se conjugue « il a ». « À » est une préposition de lieu.',
      difficulty: 2,
    },
    {
      id: 'f35',
      question: 'Complétez avec est ou et : « Marie ___ gentille ___ patiente. »',
      options: ['est / et', 'et / est', 'est / est', 'et / et'],
      answer: 0,
      explanation: '« Est » = verbe être. « Et » = conjonction qui relie deux adjectifs.',
      difficulty: 2,
    },
    {
      id: 'f36',
      question: 'Complétez avec on ou ont : « Les enfants ___ faim. »',
      options: ['on', 'ont', 'ons', 'onts'],
      answer: 1,
      explanation: '« Avoir » à la 3e personne du pluriel : ils ont faim.',
      difficulty: 2,
    },
    {
      id: 'f37',
      question: 'Quel mot appartient à la même famille que « école » ?',
      options: ['Écolier', 'Écouter', 'Échelle', 'Éclair'],
      answer: 0,
      explanation: 'La famille de mots partage la même racine : école → écolier, scolaire…',
      difficulty: 1,
    },
    {
      id: 'f38',
      question: 'Quels mots font partie du champ lexical du « sport » ?',
      options: ['Ballon, match, équipe', 'Table, chaise, bureau', 'Mer, poisson, bateau', 'Livre, page, chapitre'],
      answer: 0,
      explanation: 'Le champ lexical regroupe les mots du même thème : sport → ballon, match, équipe.',
      difficulty: 1,
    },
    {
      id: 'f39',
      question: 'Quel est le contraire de « ancien » (pour une chose) ?',
      options: ['Vieux', 'Neuf', 'Lourd', 'Lent'],
      answer: 1,
      explanation: 'Pour un objet, le contraire d\'« ancien » est souvent « neuf » (récent).',
      difficulty: 1,
    },
    {
      id: 'f40',
      question: 'Un texte qui raconte une histoire avec des personnages est surtout :',
      options: ['Descriptif', 'Narratif', 'Argumentatif', 'Informatif pur'],
      answer: 1,
      explanation: 'Le récit (narration) présente des événements dans le temps : texte narratif.',
      difficulty: 2,
    },
    {
      id: 'f41',
      question: 'Dans une lettre, où place-t-on en général la formule de politesse finale ?',
      options: ['Au milieu du texte', 'Après le corps de la lettre, avant la signature', 'Avant le titre', 'Dans l\'en-tête seulement'],
      answer: 1,
      explanation: 'La formule de politesse (« Cordialement », « Amitiés »…) vient après le texte et avant la signature.',
      difficulty: 1,
    },
    {
      id: 'f42',
      question: 'Quelle phrase utilise correctement « c\'est » ?',
      options: ['C\'est les élèves qui étudient.', 'Ce sont les élèves qui étudient.', 'C\'est des élèves qui étudient.', 'Ses les élèves qui étudient.'],
      answer: 1,
      explanation: 'Avec un pluriel, on emploie souvent « Ce sont » + les + nom pluriel.',
      difficulty: 3,
    },
    {
      id: 'f43',
      question: 'Quel est le participe passé correct : « Elles sont ___ » (partir)',
      options: ['parties', 'partis', 'partit', 'partant'],
      answer: 0,
      explanation: 'Avec « être », le participe passé s\'accorde avec le sujet féminin pluriel : elles sont parties.',
      difficulty: 2,
    },
    {
      id: 'f44',
      question: 'Identifiez l\'infinitif du verbe conjugué : « nous finissons »',
      options: ['Finir', 'Finissons', 'Finissant', 'Finissait'],
      answer: 0,
      explanation: '« Finissons » vient du verbe « finir » à l\'indicatif présent (nous finissons). L\'infinitif est finir.',
      difficulty: 2,
    },
    {
      id: 'f45',
      question: '« Ni… ni » dans « Il n\'a ni stylo ni gomme » exprime :',
      options: ['Une alternative', 'Une double négation / absence', 'Une comparaison', 'Une cause'],
      answer: 1,
      explanation: '« Ni… ni » nie deux éléments : il n\'a pas de stylo et pas de gomme.',
      difficulty: 2,
    },
    {
      id: 'f46',
      question: 'Quelle proposition est une subordonnée relative ?',
      options: ['Le livre que j\'ai lu.', 'Il court vite.', 'Parce qu\'il pleut.', 'S\'il fait beau.'],
      answer: 0,
      explanation: '« Que j\'ai lu » complète « le livre » et est introduite par un pronom relatif — relative.',
      difficulty: 3,
    },
    {
      id: 'f47',
      question: 'Le féminin de « acteur » est :',
      options: ['Acteuse', 'Actrice', 'Acteuresse', 'Acteure'],
      answer: 1,
      explanation: 'Acteur → actrice (terminaison en -ice pour certains noms d\'agent).',
      difficulty: 1,
    },
    {
      id: 'f48',
      question: 'Quelle phrase est correctement orthographiée ?',
      options: [
        'Il habite à Nouakchott.',
        'Il habite a Nouakchott.',
        'Il habbite à Nouakchott.',
        'Il habite à nouakchott.',
      ],
      answer: 0,
      explanation: '« À » (préposition) devant un nom de lieu ; « Nouakchott » avec majuscule ; une seule consonne dans « habite ».',
      difficulty: 2,
    },
    {
      id: 'f49',
      question: 'Complétez : « ___ ami m\'a prêté un livre. » (démonstratif, masculin devant voyelle)',
      options: ['Ce', 'Cet', 'Cette', 'Ces'],
      answer: 1,
      explanation: 'Devant un nom masculin commençant par une voyelle, on utilise « cet » : cet ami.',
      difficulty: 2,
    },
    {
      id: 'f50',
      question: 'Dans « Les nuages blancs flottent dans le ciel », « blancs » s\'accorde avec :',
      options: ['nuages', 'flottent', 'dans', 'ciel'],
      answer: 0,
      explanation: 'L\'adjectif « blancs » s\'accorde en genre et nombre avec « nuages » (masculin pluriel).',
      difficulty: 1,
    },
    {
      id: 'f51',
      question: 'Quelle est la valeur de « ne… plus » dans « Je ne mange plus de bonbons » ?',
      options: ['Négation totale', 'Négation partielle (plus du tout)', 'Interrogation', 'Condition'],
      answer: 1,
      explanation: '« Ne… plus » indique que l\'action ne se produit plus du tout.',
      difficulty: 2,
    },
    {
      id: 'f52',
      question: 'Synonyme de « commence » :',
      options: ['Termine', 'Débute', 'Finit', 'Arrête'],
      answer: 1,
      explanation: 'Commencer et débuter sont des synonymes proches.',
      difficulty: 1,
    },
    {
      id: 'f53',
      question: 'Quel groupe verbal : « finir » ?',
      options: ['1er groupe (-er)', '2e groupe (-ir en -issant)', '3e groupe irrégulier', 'Auxiliaire seulement'],
      answer: 1,
      explanation: 'Les verbes en -ir du 2e groupe ont « -iss- » aux présents : je finis, nous finissons.',
      difficulty: 2,
    },
    {
      id: 'f54',
      question: '« Il paraît fatigué » — « fatigué » est :',
      options: ['COD', 'Attribut du sujet', 'COI', 'Adverbe'],
      answer: 1,
      explanation: 'Avec un verbe d\'état comme « paraître », l\'adjectif est attribut du sujet.',
      difficulty: 2,
    },
    {
      id: 'f55',
      question: 'Pour rédiger un texte argumentatif, on doit surtout :',
      options: ['Raconter une histoire', 'Donner des arguments et des exemples', 'Décrire uniquement des couleurs', 'Lister des ingrédients'],
      answer: 1,
      explanation: 'Le texte argumentatif défend une opinion avec arguments, exemples et parfois conclusion.',
      difficulty: 2,
    },
  ],

  science: [
    {
      id: 's1',
      question: 'De quoi la plante a-t-elle besoin pour réaliser la photosynthèse ?',
      options: ['Eau, oxygène, obscurité', 'Lumière, CO₂, eau', 'Eau, azote, chaleur', 'Lumière, oxygène, sucre'],
      answer: 1,
      explanation: 'La photosynthèse nécessite la lumière solaire, le dioxyde de carbone (CO₂) et l\'eau pour produire du glucose et de l\'oxygène.',
      difficulty: 1,
    },
    {
      id: 's2',
      question: 'Quel organe pompel le sang dans le corps humain ?',
      options: ['Le poumon', 'Le foie', 'Le cœur', 'Le rein'],
      answer: 2,
      explanation: 'Le cœur est un muscle creux qui pompe le sang dans tout le corps grâce à ses contractions (battements).',
      difficulty: 1,
    },
    {
      id: 's3',
      question: 'Comment s\'appelle la transformation d\'une chenille en papillon ?',
      options: ['La germination', 'La métamorphose', 'La reproduction', 'La photosynthèse'],
      answer: 1,
      explanation: 'La métamorphose est la transformation d\'un animal (larve → adulte). La chenille se transforme en chrysalide puis en papillon.',
      difficulty: 1,
    },
    {
      id: 's4',
      question: 'Quel gaz est rejeté par les plantes lors de la photosynthèse ?',
      options: ['Azote (N₂)', 'Dioxyde de carbone (CO₂)', 'Oxygène (O₂)', 'Hydrogène (H₂)'],
      answer: 2,
      explanation: 'La photosynthèse produit du glucose et de l\'oxygène (O₂) qui est rejeté dans l\'atmosphère.',
      difficulty: 1,
    },
    {
      id: 's5',
      question: 'Combien de chambres (cavités) a le cœur humain ?',
      options: ['2', '3', '4', '6'],
      answer: 2,
      explanation: 'Le cœur humain a 4 cavités : 2 oreillettes (droite et gauche) et 2 ventricules (droit et gauche).',
      difficulty: 2,
    },
    {
      id: 's6',
      question: 'Qu\'est-ce qu\'un herbivore ?',
      options: [
        'Un animal qui mange de la viande',
        'Un animal qui mange des plantes',
        'Un animal qui mange tout',
        'Un animal qui mange des insectes',
      ],
      answer: 1,
      explanation: 'Un herbivore se nourrit uniquement de végétaux (herbe, feuilles, fruits). Ex : la vache, le lapin.',
      difficulty: 1,
    },
    {
      id: 's7',
      question: 'Quel est le rôle des racines pour la plante ?',
      options: [
        'Fabriquer la chlorophylle',
        'Absorber l\'eau et les sels minéraux du sol',
        'Capter la lumière solaire',
        'Produire les graines',
      ],
      answer: 1,
      explanation: 'Les racines ancrent la plante dans le sol et absorbent l\'eau et les sels minéraux nécessaires à sa croissance.',
      difficulty: 1,
    },
    {
      id: 's8',
      question: 'Comment s\'appelle le squelette externe de certains animaux (insectes, crabes) ?',
      options: ['Endosquelette', 'Exosquelette', 'Carapace molle', 'Dermosquelette'],
      answer: 1,
      explanation: 'L\'exosquelette est une enveloppe rigide externe. Les insectes, crustacés et araignées en sont dotés.',
      difficulty: 2,
    },
    {
      id: 's9',
      question: 'Quel est le circuit de l\'air lors de la respiration ?',
      options: [
        'Bouche → estomac → sang',
        'Nez/bouche → trachée → bronches → poumons',
        'Nez → cœur → poumons',
        'Poumons → trachée → sang',
      ],
      answer: 1,
      explanation: 'L\'air entre par le nez/bouche, descend dans la trachée, se divise dans les bronches et arrive aux poumons où ont lieu les échanges gazeux.',
      difficulty: 2,
    },
    {
      id: 's10',
      question: 'Qu\'est-ce que la chaîne alimentaire ?',
      options: [
        'Une liste de repas pour animaux',
        'La suite d\'êtres vivants dont chacun mange le précédent',
        'Le cycle de l\'eau dans la nature',
        'La transformation des plantes en énergie',
      ],
      answer: 1,
      explanation: 'Une chaîne alimentaire montre les relations de prédation. Ex : herbe → lapin → renard → aigle.',
      difficulty: 1,
    },
    {
      id: 's11',
      question: 'Qu\'est-ce que la germination ?',
      options: [
        'La chute des feuilles en automne',
        'Le développement d\'une graine en jeune plante',
        'La reproduction des animaux',
        'La transformation de la sève en sucre',
      ],
      answer: 1,
      explanation: 'La germination est le processus par lequel une graine se développe pour donner naissance à une jeune plante (plantule).',
      difficulty: 1,
    },
    {
      id: 's12',
      question: 'De quoi est composée l\'eau pure ?',
      options: ['H₂O₂', 'H₂O', 'HO', 'H₃O'],
      answer: 1,
      explanation: 'L\'eau pure est composée de 2 atomes d\'hydrogène (H) et 1 atome d\'oxygène (O), soit H₂O.',
      difficulty: 2,
    },
    {
      id: 's13',
      question: 'Quel organe du corps humain filtre le sang et produit l\'urine ?',
      options: ['Le foie', 'Le cœur', 'Le rein', 'La rate'],
      answer: 2,
      explanation: 'Les reins filtrent les déchets du sang et produisent l\'urine qui est ensuite éliminée.',
      difficulty: 2,
    },
    {
      id: 's14',
      question: 'Quel est le nom du processus par lequel l\'eau liquide devient vapeur ?',
      options: ['Condensation', 'Précipitation', 'Évaporation', 'Solidification'],
      answer: 2,
      explanation: 'L\'évaporation est le passage de l\'eau de l\'état liquide à l\'état gazeux (vapeur d\'eau).',
      difficulty: 1,
    },
    {
      id: 's15',
      question: 'Lequel de ces animaux est un mammifère ?',
      options: ['Le crocodile', 'Le serpent', 'La baleine', 'L\'aigle'],
      answer: 2,
      explanation: 'La baleine est un mammifère marin (elle respire de l\'air, allaite ses petits). Le crocodile et le serpent sont des reptiles, l\'aigle est un oiseau.',
      difficulty: 2,
    },
    {
      id: 's16',
      question: 'Quelle partie de la plante absorbe l\'énergie lumineuse ?',
      options: ['La racine', 'La tige', 'La feuille', 'La fleur'],
      answer: 2,
      explanation: 'Les feuilles contiennent la chlorophylle, le pigment vert qui capture l\'énergie lumineuse pour la photosynthèse.',
      difficulty: 1,
    },
    {
      id: 's17',
      question: 'Comment appelle-t-on les animaux qui mangent à la fois des plantes et de la viande ?',
      options: ['Herbivores', 'Carnivores', 'Omnivores', 'Insectivores'],
      answer: 2,
      explanation: 'Les omnivores mangent des aliments d\'origine végétale et animale. L\'homme et l\'ours sont omnivores.',
      difficulty: 1,
    },
    {
      id: 's18',
      question: 'Quel est le rôle du système digestif ?',
      options: [
        'Pomper le sang dans le corps',
        'Transformer les aliments en nutriments assimilables',
        'Filtrer l\'air que l\'on respire',
        'Protéger le corps contre les microbes',
      ],
      answer: 1,
      explanation: 'Le système digestif transforme les aliments en nutriments que le sang peut transporter vers les cellules du corps.',
      difficulty: 1,
    },
    {
      id: 's19',
      question: 'Qu\'est-ce qu\'un écosystème ?',
      options: [
        'Un groupe d\'animaux de la même espèce',
        'L\'ensemble des êtres vivants et leur milieu naturel en interaction',
        'Une réserve naturelle protégée',
        'Le cycle de reproduction des plantes',
      ],
      answer: 1,
      explanation: 'Un écosystème est un ensemble formé par les êtres vivants (biocénose) et leur environnement physique (biotope) en interaction.',
      difficulty: 2,
    },
    {
      id: 's20',
      question: 'Quelle couche de l\'atmosphère nous protège des rayons UV du soleil ?',
      options: ['La troposphère', 'La stratosphère avec la couche d\'ozone', 'La mésosphère', 'L\'ionosphère'],
      answer: 1,
      explanation: 'La couche d\'ozone (O₃), située dans la stratosphère, absorbe la majorité des rayons ultraviolets nocifs du soleil.',
      difficulty: 3,
    },
  ],

  // ─── اللغة العربية ──────────────────────────────────────────────────────────
  arabe: [
    {
      id: 'ar1',
      question: 'ما هو الفاعل في الجملة: "كتبَ الطالبُ الدرسَ"؟',
      options: ['الدرسَ', 'الطالبُ', 'كتبَ', 'لا يوجد فاعل'],
      answer: 1,
      explanation: 'الفاعل هو الاسم الذي يدل على من قام بالفعل. في هذه الجملة، "الطالبُ" هو الذي قام بالكتابة.',
      difficulty: 1,
    },
    {
      id: 'ar2',
      question: 'أيٌّ من هذه الكلمات جمعٌ مذكرٌ سالم؟',
      options: ['رجال', 'أقلام', 'معلمون', 'كتب'],
      answer: 2,
      explanation: 'الجمع المذكر السالم يُجمع بإضافة "ون" أو "ين" للمفرد المذكر. "معلمون" جمع مذكر سالم لـ"معلم".',
      difficulty: 1,
    },
    {
      id: 'ar3',
      question: 'ما نوع الفعل "يلعبُ" من حيث الزمن؟',
      options: ['فعل ماضٍ', 'فعل مضارع', 'فعل أمر', 'مصدر'],
      answer: 1,
      explanation: 'الفعل المضارع يدل على حدث يقع في الزمن الحاضر أو المستقبل، ويبدأ بأحد حروف "أ، ن، ي، ت" (أنيت). "يلعب" فعل مضارع.',
      difficulty: 1,
    },
    {
      id: 'ar4',
      question: 'ما مفرد كلمة "أقلام"؟',
      options: ['قلامة', 'قلم', 'أقلم', 'قليم'],
      answer: 1,
      explanation: '"أقلام" جمع تكسير، ومفرده "قَلَم".',
      difficulty: 1,
    },
    {
      id: 'ar5',
      question: 'أكمل: "ذهبَ الولدُ إلى ___" — ما الإعراب الصحيح للكلمة الأخيرة؟',
      options: ['مرفوع', 'منصوب', 'مجرور', 'مجزوم'],
      answer: 2,
      explanation: 'الاسم بعد حرف الجر يكون مجروراً. "إلى" حرف جر، والاسم بعده مجرور بالكسرة.',
      difficulty: 2,
    },
    {
      id: 'ar6',
      question: 'ما علامة جزم الفعل المضارع الصحيح؟',
      options: ['الفتحة', 'الضمة', 'السكون', 'الكسرة'],
      answer: 2,
      explanation: 'الفعل المضارع الصحيح يُجزم بالسكون. مثال: "لم يكتبْ".',
      difficulty: 2,
    },
    {
      id: 'ar7',
      question: 'في جملة "إنَّ الطالبَ مجتهدٌ" — ما إعراب "الطالبَ"؟',
      options: ['مبتدأ مرفوع', 'اسم إن منصوب', 'خبر إن مرفوع', 'فاعل مرفوع'],
      answer: 1,
      explanation: '"إنَّ" من الحروف الناسخة تنصب المبتدأ ويُسمى اسمها. "الطالبَ" اسم إن منصوب بالفتحة.',
      difficulty: 2,
    },
    {
      id: 'ar8',
      question: 'ما المقصود بالمفعول به؟',
      options: [
        'الاسم الذي يدل على من قام بالفعل',
        'الاسم الواقع على الحدث',
        'الاسم المجرور بحرف جر',
        'الفعل في زمن الماضي',
      ],
      answer: 1,
      explanation: 'المفعول به هو الاسم الذي وقع عليه فعل الفاعل. مثال: "قرأَ الطالبُ الكتابَ" — الكتابَ هو المفعول به.',
      difficulty: 1,
    },
    {
      id: 'ar9',
      question: 'أيٌّ من هذه الجمل تحتوي على ضمير متصل؟',
      options: ['ذهب هو', 'كتابه على الطاولة', 'أنتَ مجتهد', 'هم يلعبون'],
      answer: 1,
      explanation: 'الضمير المتصل يتصل بالكلمة كالهاء في "كتابه". أما "هو" و"أنت" و"هم" فهي ضمائر منفصلة.',
      difficulty: 2,
    },
    {
      id: 'ar10',
      question: 'ما جمع كلمة "مدرسة"؟',
      options: ['مدرسون', 'مدارس', 'مدرستان', 'مدرسات'],
      answer: 1,
      explanation: '"مدارس" جمع تكسير لـ"مدرسة". أما "مدرسات" فهو جمع مؤنث سالم.',
      difficulty: 1,
    },
    {
      id: 'ar11',
      question: 'ما نوع الأسلوب في الجملة: "اكتبْ دروسَك"؟',
      options: ['أسلوب خبر', 'أسلوب نهي', 'أسلوب أمر', 'أسلوب استفهام'],
      answer: 2,
      explanation: 'أسلوب الأمر يطلب القيام بفعل. الجملة تبدأ بفعل أمر "اكتبْ".',
      difficulty: 1,
    },
    {
      id: 'ar12',
      question: 'ما الفرق بين الفعل الماضي والمضارع؟',
      options: [
        'الماضي للمستقبل، المضارع للماضي',
        'الماضي لحدث انتهى، المضارع لحدث يجري أو سيجري',
        'لا فرق بينهما',
        'الماضي مجهول والمضارع معلوم',
      ],
      answer: 1,
      explanation: 'الفعل الماضي يدل على حدث تم وانتهى. الفعل المضارع يدل على حدث يحدث الآن أو سيحدث.',
      difficulty: 1,
    },
    {
      id: 'ar13',
      question: 'حدِّد الصفة في: "قرأتُ كتاباً مفيداً"',
      options: ['قرأتُ', 'كتاباً', 'مفيداً', 'لا توجد صفة'],
      answer: 2,
      explanation: 'النعت (الصفة) يصف الاسم قبله. "مفيداً" نعت لـ"كتاباً" وتبعه في التنكير والنصب.',
      difficulty: 2,
    },
    {
      id: 'ar14',
      question: 'ما إعراب "محمدٌ" في: "محمدٌ طالبٌ مجتهدٌ"؟',
      options: ['فاعل مرفوع', 'مبتدأ مرفوع', 'خبر مرفوع', 'مفعول به منصوب'],
      answer: 1,
      explanation: 'في الجملة الاسمية، الاسم الأول يُسمى المبتدأ وهو مرفوع. "محمدٌ" مبتدأ مرفوع بالضمة.',
      difficulty: 2,
    },
    {
      id: 'ar15',
      question: 'أيٌّ من هذه الكلمات مؤنث؟',
      options: ['كتاب', 'قلم', 'مدرسة', 'باب'],
      answer: 2,
      explanation: 'المؤنث اللفظي غالباً ينتهي بتاء مربوطة (ة). "مدرسة" مؤنث لأنها تنتهي بتاء مربوطة.',
      difficulty: 1,
    },
  ],

  // ─── التاريخ والجغرافيا ──────────────────────────────────────────────────────
  histoire_geo: [
    {
      id: 'hg1',
      question: 'ما عاصمة موريتانيا؟',
      options: ['نواذيبو', 'روصو', 'نواكشوط', 'كيفة'],
      answer: 2,
      explanation: 'نواكشوط هي عاصمة الجمهورية الإسلامية الموريتانية ومركزها السياسي والإداري.',
      difficulty: 1,
    },
    {
      id: 'hg2',
      question: 'على أي محيط تطل موريتانيا؟',
      options: ['المحيط الهندي', 'المحيط الهادئ', 'المحيط الأطلسي', 'المحيط المتجمد'],
      answer: 2,
      explanation: 'تطل موريتانيا على المحيط الأطلسي من الجهة الغربية بساحل يمتد لأكثر من 700 كيلومتر.',
      difficulty: 1,
    },
    {
      id: 'hg3',
      question: 'ما أكبر صحراء في العالم؟',
      options: ['صحراء العرب', 'صحراء جوبي', 'الصحراء الكبرى', 'صحراء كالاهاري'],
      answer: 2,
      explanation: 'الصحراء الكبرى (Sahara) في أفريقيا هي أكبر صحراء حارة في العالم. تغطي معظم شمال أفريقيا بما فيها موريتانيا.',
      difficulty: 1,
    },
    {
      id: 'hg4',
      question: 'ما النهر الرئيسي الذي يحدّ موريتانيا من الجنوب؟',
      options: ['نهر النيل', 'نهر السنغال', 'نهر النيجر', 'نهر الكونغو'],
      answer: 1,
      explanation: 'نهر السنغال يشكّل الحدود الطبيعية بين موريتانيا والسنغال في الجنوب.',
      difficulty: 1,
    },
    {
      id: 'hg5',
      question: 'متى نالت موريتانيا استقلالها؟',
      options: ['1958', '1960', '1962', '1956'],
      answer: 1,
      explanation: 'نالت موريتانيا استقلالها عن فرنسا في 28 نوفمبر 1960، وهو تاريخ العيد الوطني الموريتاني.',
      difficulty: 1,
    },
    {
      id: 'hg6',
      question: 'كم عدد قارات العالم؟',
      options: ['5', '6', '7', '8'],
      answer: 2,
      explanation: 'يتكوّن العالم من 7 قارات: آسيا، أفريقيا، أمريكا الشمالية، أمريكا الجنوبية، أنتاركتيكا، أوروبا، وأستراليا.',
      difficulty: 1,
    },
    {
      id: 'hg7',
      question: 'أيٌّ من هذه المدن تقع في موريتانيا؟',
      options: ['داكار', 'نواذيبو', 'باماكو', 'الرباط'],
      answer: 1,
      explanation: 'نواذيبو هي ثاني أكبر مدينة موريتانية وميناؤها الرئيسي على المحيط الأطلسي.',
      difficulty: 1,
    },
    {
      id: 'hg8',
      question: 'ما أطول نهر في العالم؟',
      options: ['نهر الأمازون', 'نهر النيل', 'نهر المسيسيبي', 'نهر اليانغتسي'],
      answer: 1,
      explanation: 'نهر النيل في أفريقيا هو أطول أنهار العالم بطول يبلغ حوالي 6650 كيلومتراً.',
      difficulty: 1,
    },
    {
      id: 'hg9',
      question: 'ما المناخ السائد في معظم موريتانيا؟',
      options: ['مناخ استوائي', 'مناخ صحراوي جاف', 'مناخ معتدل', 'مناخ قطبي'],
      answer: 1,
      explanation: 'يسود موريتانيا المناخ الصحراوي الجاف في معظم أراضيها، مع مناخ ساحلي في الغرب وشبه جاف في الجنوب.',
      difficulty: 1,
    },
    {
      id: 'hg10',
      question: 'ما أكبر قارة في العالم من حيث المساحة؟',
      options: ['أفريقيا', 'أمريكا الشمالية', 'آسيا', 'أوروبا'],
      answer: 2,
      explanation: 'آسيا هي أكبر قارة في العالم بمساحة تبلغ حوالي 44.6 مليون كيلومتر مربع.',
      difficulty: 1,
    },
    {
      id: 'hg11',
      question: 'ما الدول المحيطة بموريتانيا؟',
      options: [
        'المغرب والجزائر ومالي والسنغال وغينيا بيساو',
        'المغرب والجزائر ومالي والسنغال',
        'الجزائر ومالي والسنغال',
        'المغرب وليبيا والسنغال',
      ],
      answer: 1,
      explanation: 'تحدّ موريتانيا: المغرب وإقليم الصحراء الغربية شمالاً، الجزائر شمالاً شرقاً، مالي شرقاً وجنوباً، السنغال جنوباً.',
      difficulty: 2,
    },
    {
      id: 'hg12',
      question: 'أيٌّ من هذه الإمبراطوريات قامت في غرب أفريقيا؟',
      options: ['إمبراطورية الرومان', 'إمبراطورية غانا', 'إمبراطورية الفرس', 'الإمبراطورية العثمانية'],
      answer: 1,
      explanation: 'إمبراطورية غانا كانت من أوائل الإمبراطوريات الكبرى في غرب أفريقيا (ق4 - ق13 ميلادي).',
      difficulty: 2,
    },
    {
      id: 'hg13',
      question: 'ما مصدر الثروة الرئيسي في موريتانيا؟',
      options: ['الزراعة', 'الصناعة', 'الثروة السمكية والمعادن', 'السياحة'],
      answer: 2,
      explanation: 'تعتمد موريتانيا على الثروة السمكية (ساحل أطلسي غني) وخام الحديد في الشمال وحديثاً النفط والغاز الطبيعي.',
      difficulty: 2,
    },
    {
      id: 'hg14',
      question: 'في أي قارة تقع موريتانيا؟',
      options: ['آسيا', 'أوروبا', 'أفريقيا', 'أمريكا'],
      answer: 2,
      explanation: 'موريتانيا تقع في شمال غرب القارة الأفريقية.',
      difficulty: 1,
    },
    {
      id: 'hg15',
      question: 'ما اسم عملة موريتانيا؟',
      options: ['الدرهم', 'الأوقية', 'الفرنك', 'الدينار'],
      answer: 1,
      explanation: 'عملة موريتانيا هي الأوقية الموريتانية (MRU).',
      difficulty: 1,
    },
  ],

  // ─── التربية الإسلامية ──────────────────────────────────────────────────────
  islamique: [
    {
      id: 'is1',
      question: 'كم عدد أركان الإسلام؟',
      options: ['3', '4', '5', '6'],
      answer: 2,
      explanation: 'أركان الإسلام خمسة: الشهادتان، الصلاة، الزكاة، الصوم، الحج.',
      difficulty: 1,
    },
    {
      id: 'is2',
      question: 'كم عدد الصلوات المفروضة في اليوم والليلة؟',
      options: ['3', '4', '5', '6'],
      answer: 2,
      explanation: 'الصلوات المفروضة خمس: الفجر، الظهر، العصر، المغرب، العشاء.',
      difficulty: 1,
    },
    {
      id: 'is3',
      question: 'ما أول ركن من أركان الإسلام؟',
      options: ['الصلاة', 'الزكاة', 'شهادة أن لا إله إلا الله', 'الصوم'],
      answer: 2,
      explanation: 'أول أركان الإسلام هو الشهادتان: "أشهد أن لا إله إلا الله وأن محمداً رسول الله".',
      difficulty: 1,
    },
    {
      id: 'is4',
      question: 'ما الشهر الذي يصوم فيه المسلمون؟',
      options: ['شعبان', 'رمضان', 'ذو الحجة', 'محرم'],
      answer: 1,
      explanation: 'رمضان هو الشهر التاسع في التقويم الهجري، وهو شهر الصيام المفروض على المسلمين.',
      difficulty: 1,
    },
    {
      id: 'is5',
      question: 'إلى أين يتجه المسلمون في صلاتهم؟',
      options: ['بيت المقدس', 'المدينة المنورة', 'الكعبة المشرفة في مكة', 'القاهرة'],
      answer: 2,
      explanation: 'يتجه المسلمون في صلاتهم نحو الكعبة المشرفة في مكة المكرمة (القبلة).',
      difficulty: 1,
    },
    {
      id: 'is6',
      question: 'ما آخر الأنبياء والرسل؟',
      options: ['عيسى عليه السلام', 'موسى عليه السلام', 'إبراهيم عليه السلام', 'محمد صلى الله عليه وسلم'],
      answer: 3,
      explanation: 'محمد صلى الله عليه وسلم هو خاتم الأنبياء والمرسلين.',
      difficulty: 1,
    },
    {
      id: 'is7',
      question: 'كم عدد أركان الإيمان؟',
      options: ['4', '5', '6', '7'],
      answer: 2,
      explanation: 'أركان الإيمان ستة: الإيمان بالله، وملائكته، وكتبه، ورسله، واليوم الآخر، والقدر خيره وشره.',
      difficulty: 1,
    },
    {
      id: 'is8',
      question: 'ما الكتاب المنزَّل على النبي محمد ﷺ؟',
      options: ['التوراة', 'الإنجيل', 'القرآن الكريم', 'الزبور'],
      answer: 2,
      explanation: 'القرآن الكريم هو كتاب الله المنزَّل على النبي محمد ﷺ، وهو آخر الكتب السماوية.',
      difficulty: 1,
    },
    {
      id: 'is9',
      question: 'ما معنى كلمة "الزكاة" في الإسلام؟',
      options: [
        'الصلاة في الليل',
        'الصوم الاختياري',
        'جزء من المال يُعطى للفقراء',
        'الحج إلى مكة',
      ],
      answer: 2,
      explanation: 'الزكاة ركن من أركان الإسلام، وهي مقدار مال واجب يُخرجه المسلم لمستحقيه من فقراء ومساكين وغيرهم.',
      difficulty: 1,
    },
    {
      id: 'is10',
      question: 'ما الخُلُق الذي يأمرنا به الإسلام في التعامل مع الوالدين؟',
      options: ['العقوق', 'البر والإحسان', 'الإهمال', 'المعصية'],
      answer: 1,
      explanation: 'أمر الإسلام ببر الوالدين والإحسان إليهما، قال الله تعالى: "وبالوالدين إحساناً".',
      difficulty: 1,
    },
    {
      id: 'is11',
      question: 'كم ركعة في صلاة المغرب؟',
      options: ['2', '3', '4', '5'],
      answer: 1,
      explanation: 'صلاة المغرب ثلاث ركعات: ركعتان جهريتان وركعة سرية.',
      difficulty: 1,
    },
    {
      id: 'is12',
      question: 'ما أعظم سورة في القرآن الكريم؟',
      options: ['سورة البقرة', 'سورة الفاتحة', 'سورة الإخلاص', 'سورة الناس'],
      answer: 1,
      explanation: 'سورة الفاتحة هي أم القرآن وأعظم سورة فيه، وتُقرأ في كل ركعة من ركعات الصلاة.',
      difficulty: 1,
    },
    {
      id: 'is13',
      question: 'ما الصفة المقابلة للكذب؟',
      options: ['الغيبة', 'الصدق', 'النفاق', 'الحسد'],
      answer: 1,
      explanation: 'الصدق هو قول الحق والأمانة في الكلام، وهو من أهم الأخلاق الإسلامية المقابلة للكذب.',
      difficulty: 1,
    },
    {
      id: 'is14',
      question: 'في أي مدينة وُلد النبي محمد ﷺ؟',
      options: ['المدينة المنورة', 'مكة المكرمة', 'الطائف', 'جدة'],
      answer: 1,
      explanation: 'وُلد النبي محمد ﷺ في مكة المكرمة عام الفيل.',
      difficulty: 1,
    },
    {
      id: 'is15',
      question: 'ما معنى "الصيام"؟',
      options: [
        'قراءة القرآن فقط',
        'الامتناع عن الطعام والشراب من الفجر إلى المغرب',
        'صلاة الليل',
        'التصدق على الفقراء',
      ],
      answer: 1,
      explanation: 'الصيام هو الامتناع عن الطعام والشراب وسائر المفطرات من طلوع الفجر إلى غروب الشمس.',
      difficulty: 1,
    },
  ],

  // ── Packs 6AF arabes (QCM liés aux QR des cahiers imprimés) ──
  'math6-ar': [...MATH6_EXERCISES_1, ...MATH6_EXERCISES_2],
  'sci6-ar': SCI6_EXERCISES,
  ar6: [...AR6_EXERCISES_1, ...AR6_EXERCISES_2],
  isl6: ISL6_EXERCISES,
  hg6: [...HG6_EXERCISES_1, ...HG6_EXERCISES_2],
  civ6: CIV6_EXERCISES,
};

export const SUBJECTS = [
  {
    id: 'french',
    label: 'Français',
    labelAr: 'الفرنسية',
    icon: '📖',
    color: '#38bdf8',
    colorDark: '#0284c7',
    colorBg: '#e0f2fe',
    exercises: EXERCISES.french,
  },
  {
    id: 'math',
    label: 'Mathématiques',
    labelAr: 'الرياضيات',
    icon: '📐',
    color: '#fb923c',
    colorDark: '#ea580c',
    colorBg: '#fff7ed',
    exercises: EXERCISES.math,
  },
  {
    id: 'science',
    label: 'Sciences',
    labelAr: 'العلوم',
    icon: '🔬',
    color: '#34d399',
    colorDark: '#059669',
    colorBg: '#ecfdf5',
    exercises: EXERCISES.science,
  },

  // ─── Matières arabes ────────────────────────────────────────────────────────
  {
    id: 'arabe',
    label: 'Arabe',
    labelAr: 'اللغة العربية',
    icon: '🕌',
    color: '#06803C',
    colorDark: '#065f46',
    colorBg: '#d1fae5',
    isArabic: true,
    exercises: EXERCISES.arabe,
  },
  {
    id: 'histoire_geo',
    label: 'Histoire-Géo',
    labelAr: 'التاريخ والجغرافيا',
    icon: '🌍',
    color: '#8b5cf6',
    colorDark: '#6d28d9',
    colorBg: '#ede9fe',
    isArabic: true,
    exercises: EXERCISES.histoire_geo,
  },
  {
    id: 'islamique',
    label: 'Islamique',
    labelAr: 'التربية الإسلامية',
    icon: '☪️',
    color: '#059669',
    colorDark: '#047857',
    colorBg: '#ecfdf5',
    isArabic: true,
    exercises: EXERCISES.islamique,
  },

  // ── Packs 6AF arabes (cahiers Major imprimés) ──
  {
    id: 'math6-ar',
    label: 'Mathématiques 6AF',
    labelAr: 'الرياضيات',
    icon: '📐',
    color: '#fb923c',
    colorDark: '#ea580c',
    colorBg: '#fff7ed',
    isArabic: true,
    exercises: EXERCISES['math6-ar'],
  },
  {
    id: 'sci6-ar',
    label: 'Sciences naturelles 6AF',
    labelAr: 'العلوم الطبيعية',
    icon: '🔬',
    color: '#34d399',
    colorDark: '#059669',
    colorBg: '#ecfdf5',
    isArabic: true,
    exercises: EXERCISES['sci6-ar'],
  },
  {
    id: 'ar6',
    label: 'Arabe 6AF',
    labelAr: 'اللغة العربية',
    icon: '📘',
    color: '#7c3aed',
    colorDark: '#5b21b6',
    colorBg: '#f3f0ff',
    isArabic: true,
    exercises: EXERCISES.ar6,
  },
  {
    id: 'isl6',
    label: 'Islamique 6AF',
    labelAr: 'التربية الإسلامية',
    icon: '☪️',
    color: '#0d9488',
    colorDark: '#0f766e',
    colorBg: '#e7f8f4',
    isArabic: true,
    exercises: EXERCISES.isl6,
  },
];
